import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";
import {
  Accessibility,
  Activity,
  AlarmClock,
  Ambulance,
  Anchor,
  Antenna,
  Aperture,
  Apple,
  Archive,
  Armchair,
  Atom,
  AudioLines,
  Award,
  Baby,
  BadgeCheck,
  Balloon,
  Banana,
  BarChart3,
  Barcode,
  Bath,
  Battery,
  BatteryCharging,
  BedDouble,
  Beer,
  Bell,
  Bike,
  Binary,
  Biohazard,
  Bird,
  Bitcoin,
  Blocks,
  Bluetooth,
  Bookmark,
  BookCopy,
  BookDashed,
  BookMarked,
  BookOpen,
  BookText,
  Bot,
  Boxes,
  Braces,
  Brackets,
  Brain,
  Briefcase,
  Building2,
  Bug,
  Bus,
  Cable,
  Cake,
  Calendar,
  Camera,
  Car,
  CarFront,
  Castle,
  Cat,
  ChefHat,
  Cherry,
  Church,
  Circle,
  CircuitBoard,
  Clapperboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Code,
  Coffee,
  Compass,
  Component,
  Contact,
  Cookie,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  CupSoda,
  Database,
  Dice5,
  Dog,
  Donut,
  DraftingCompass,
  Drama,
  Droplets,
  Dumbbell,
  Ear,
  Earth,
  EarthLock,
  Eraser,
  Eye,
  Factory,
  Fan,
  FerrisWheel,
  FileAudio,
  FileCode2,
  FileImage,
  FileJson,
  FileMusic,
  FileSpreadsheet,
  Files,
  FileText,
  FileVideo,
  Film,
  Fingerprint,
  Fish,
  Flame,
  FlaskConical,
  Flashlight,
  Flower2,
  Focus,
  FolderArchive,
  FolderClosed,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKanban,
  FolderLock,
  FolderOpen,
  FolderSearch,
  FolderSync,
  FolderTree,
  GalleryVerticalEnd,
  Gamepad2,
  GaugeCircle,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  Glasses,
  Globe,
  Globe2,
  GlobeLock,
  GraduationCap,
  Grape,
  Guitar,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hexagon,
  Hospital,
  Hourglass,
  House,
  IceCreamCone,
  Image,
  Images,
  Inbox,
  Joystick,
  Keyboard,
  KeyRound,
  Landmark,
  Lamp,
  LampDesk,
  Laptop,
  Layers,
  Leaf,
  Library,
  LibraryBig,
  Lightbulb,
  LineChart,
  ListMusic,
  ListTodo,
  Lock,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPinned,
  Martini,
  Medal,
  Megaphone,
  MemoryStick,
  MessageCircle,
  MessagesSquare,
  Mic,
  MicVocal,
  Microscope,
  Milestone,
  Monitor,
  Moon,
  MoonStar,
  Mountain,
  Mouse,
  Music,
  Music2,
  Navigation,
  Network,
  Newspaper,
  Nfc,
  Notebook,
  NotebookPen,
  Octagon,
  Orbit,
  Origami,
  Package,
  Paintbrush,
  Palette,
  Palmtree,
  PanelLeft,
  Paperclip,
  PartyPopper,
  PawPrint,
  Pentagon,
  PenLine,
  PenTool,
  Phone,
  Piano,
  PieChart,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Plug2,
  PlugZap,
  Podcast,
  Popcorn,
  Printer,
  Puzzle,
  QrCode,
  Radiation,
  Radio,
  RadioTower,
  Rainbow,
  Recycle,
  Regex,
  Ribbon,
  Rocket,
  Route,
  Rss,
  Ruler,
  Sailboat,
  Sandwich,
  Salad,
  Satellite,
  ScanFace,
  School,
  Scissors,
  Send,
  ServerCog,
  ServerCrash,
  Shapes,
  Shell,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Signal,
  SignalHigh,
  Signpost,
  Skull,
  Smartphone,
  Snail,
  Snowflake,
  Soup,
  Space,
  Sparkle,
  Sparkles,
  Speaker,
  Spline,
  Square,
  SquareKanban,
  SquareTerminal,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Sunrise,
  Sunset,
  SwatchBook,
  Swords,
  Syringe,
  Target,
  Telescope,
  Tent,
  Terminal,
  Thermometer,
  Timer,
  Tornado,
  TowerControl,
  ToyBrick,
  Tractor,
  TrainFront,
  TreePine,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Usb,
  UserRound,
  Users,
  Utensils,
  Wallet,
  WalletCards,
  Wand,
  WandSparkles,
  Watch,
  Waves,
  Waypoints,
  Webhook,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Zap,
} from "lucide-react";

export interface ProjectIconEntry {
  /** Stable kebab-case id persisted as `lucide:<id>` on the project. */
  readonly id: string;
  readonly Icon: typeof Rocket;
  /** Extra search terms beyond the words of the id. */
  readonly keywords?: readonly string[];
}

export interface ProjectIconCategory {
  readonly id: string;
  readonly label: MessageDescriptor;
  readonly icons: readonly ProjectIconEntry[];
}

/**
 * Curated lucide catalog offered as project icons. Every component name above
 * is verified against the installed lucide-react before being listed here.
 */
export const PROJECT_ICON_CATEGORIES: readonly ProjectIconCategory[] = [
  {
    id: "development",
    label: msg`Development`,
    icons: [
      { id: "code", Icon: Code, keywords: ["source", "programming"] },
      { id: "terminal", Icon: Terminal, keywords: ["cli", "shell", "console"] },
      { id: "square-terminal", Icon: SquareTerminal, keywords: ["cli", "shell"] },
      { id: "braces", Icon: Braces, keywords: ["json", "curly"] },
      { id: "brackets", Icon: Brackets, keywords: ["array"] },
      { id: "regex", Icon: Regex, keywords: ["pattern", "search"] },
      { id: "bug", Icon: Bug, keywords: ["issue", "error"] },
      { id: "git-branch", Icon: GitBranch, keywords: ["repo", "version"] },
      { id: "git-fork", Icon: GitFork, keywords: ["repo", "fork"] },
      { id: "git-commit", Icon: GitCommitHorizontal, keywords: ["repo", "commit"] },
      { id: "webhook", Icon: Webhook, keywords: ["api", "callback"] },
      { id: "workflow", Icon: Workflow, keywords: ["pipeline", "automation"] },
      { id: "network", Icon: Network, keywords: ["graph", "nodes"] },
      { id: "circuit-board", Icon: CircuitBoard, keywords: ["electronics", "pcb"] },
      { id: "binary", Icon: Binary, keywords: ["bits", "machine"] },
      { id: "cpu", Icon: Cpu, keywords: ["processor", "chip"] },
      { id: "database", Icon: Database, keywords: ["sql", "storage"] },
      { id: "server-cog", Icon: ServerCog, keywords: ["backend", "config"] },
      { id: "server-crash", Icon: ServerCrash, keywords: ["outage", "down"] },
      { id: "bot", Icon: Bot, keywords: ["robot", "assistant", "agent"] },
      { id: "blocks", Icon: Blocks, keywords: ["components", "modules"] },
      { id: "component", Icon: Component, keywords: ["widget", "module"] },
      { id: "layers", Icon: Layers, keywords: ["stack"] },
      { id: "spline", Icon: Spline, keywords: ["curve", "design"] },
      { id: "drafting-compass", Icon: DraftingCompass, keywords: ["drafting", "measure"] },
      { id: "file-code", Icon: FileCode2, keywords: ["source"] },
      { id: "file-json", Icon: FileJson, keywords: ["config"] },
      { id: "file-spreadsheet", Icon: FileSpreadsheet, keywords: ["excel", "csv"] },
      { id: "list-todo", Icon: ListTodo, keywords: ["tasks", "checklist"] },
      { id: "square-kanban", Icon: SquareKanban, keywords: ["board", "tasks"] },
    ],
  },
  {
    id: "files",
    label: msg`Files & folders`,
    icons: [
      { id: "folder-open", Icon: FolderOpen, keywords: ["project", "directory"] },
      { id: "folder-closed", Icon: FolderClosed, keywords: ["project", "directory"] },
      { id: "folder-git", Icon: FolderGit2, keywords: ["repo", "repository"] },
      { id: "folder-tree", Icon: FolderTree, keywords: ["structure"] },
      { id: "folder-archive", Icon: FolderArchive, keywords: ["zip", "backup"] },
      { id: "folder-heart", Icon: FolderHeart, keywords: ["favorite"] },
      { id: "folder-lock", Icon: FolderLock, keywords: ["private", "secure"] },
      { id: "folder-search", Icon: FolderSearch, keywords: ["find"] },
      { id: "folder-sync", Icon: FolderSync, keywords: ["backup", "cloud"] },
      { id: "folder-input", Icon: FolderInput, keywords: ["import"] },
      { id: "folder-kanban", Icon: FolderKanban, keywords: ["board", "tasks"] },
      { id: "files", Icon: Files, keywords: ["documents"] },
      { id: "file-text", Icon: FileText, keywords: ["document", "readme"] },
      { id: "file-image", Icon: FileImage, keywords: ["picture", "photo"] },
      { id: "file-audio", Icon: FileAudio, keywords: ["sound", "music"] },
      { id: "file-video", Icon: FileVideo, keywords: ["movie", "clip"] },
      { id: "file-music", Icon: FileMusic, keywords: ["song", "audio"] },
      { id: "archive", Icon: Archive, keywords: ["box", "backup"] },
      { id: "library", Icon: Library, keywords: ["collection", "books"] },
      { id: "library-big", Icon: LibraryBig, keywords: ["collection", "books"] },
      { id: "book-open", Icon: BookOpen, keywords: ["docs", "read"] },
      { id: "book-marked", Icon: BookMarked, keywords: ["docs", "bookmark"] },
      { id: "book-text", Icon: BookText, keywords: ["docs", "manual"] },
      { id: "book-copy", Icon: BookCopy, keywords: ["docs", "copy"] },
      { id: "book-dashed", Icon: BookDashed, keywords: ["docs", "template"] },
      { id: "notebook", Icon: Notebook, keywords: ["notes", "journal"] },
      { id: "notebook-pen", Icon: NotebookPen, keywords: ["notes", "write"] },
      { id: "sticky-note", Icon: StickyNote, keywords: ["memo", "postit"] },
      { id: "clipboard-list", Icon: ClipboardList, keywords: ["tasks", "checklist"] },
      { id: "newspaper", Icon: Newspaper, keywords: ["news", "press", "blog"] },
    ],
  },
  {
    id: "design-media",
    label: msg`Design & media`,
    icons: [
      { id: "palette", Icon: Palette, keywords: ["color", "theme", "art"] },
      { id: "paintbrush", Icon: Paintbrush, keywords: ["art", "paint"] },
      { id: "pen-line", Icon: PenLine, keywords: ["write", "draw", "blog"] },
      { id: "pen-tool", Icon: PenTool, keywords: ["vector", "bezier"] },
      { id: "swatch-book", Icon: SwatchBook, keywords: ["color", "samples"] },
      { id: "shapes", Icon: Shapes, keywords: ["geometry"] },
      { id: "origami", Icon: Origami, keywords: ["paper", "fold"] },
      { id: "image", Icon: Image, keywords: ["picture", "photo"] },
      { id: "images", Icon: Images, keywords: ["gallery", "photos"] },
      { id: "camera", Icon: Camera, keywords: ["photo", "photography"] },
      { id: "aperture", Icon: Aperture, keywords: ["photo", "lens"] },
      { id: "focus", Icon: Focus, keywords: ["target", "photo"] },
      { id: "film", Icon: Film, keywords: ["movie", "video"] },
      { id: "clapperboard", Icon: Clapperboard, keywords: ["movie", "video"] },
      { id: "popcorn", Icon: Popcorn, keywords: ["movie", "cinema"] },
      { id: "drama", Icon: Drama, keywords: ["theater", "masks"] },
      { id: "music", Icon: Music, keywords: ["song", "audio"] },
      { id: "music-2", Icon: Music2, keywords: ["song", "note"] },
      { id: "list-music", Icon: ListMusic, keywords: ["playlist"] },
      { id: "guitar", Icon: Guitar, keywords: ["instrument", "band"] },
      { id: "piano", Icon: Piano, keywords: ["instrument", "keys"] },
      { id: "audio-lines", Icon: AudioLines, keywords: ["waveform", "sound"] },
      { id: "mic", Icon: Mic, keywords: ["record", "voice"] },
      { id: "mic-vocal", Icon: MicVocal, keywords: ["voice", "sing"] },
      { id: "headphones", Icon: Headphones, keywords: ["audio", "listen"] },
      { id: "speaker", Icon: Speaker, keywords: ["audio", "sound"] },
      { id: "radio", Icon: Radio, keywords: ["broadcast", "fm"] },
      { id: "radio-tower", Icon: RadioTower, keywords: ["broadcast", "signal"] },
      { id: "podcast", Icon: Podcast, keywords: ["show", "audio"] },
      { id: "tv", Icon: Tv, keywords: ["television", "screen"] },
      { id: "gallery-vertical", Icon: GalleryVerticalEnd, keywords: ["carousel"] },
      { id: "scan-face", Icon: ScanFace, keywords: ["faceid", "biometric"] },
      { id: "qr-code", Icon: QrCode, keywords: ["scan"] },
      { id: "barcode", Icon: Barcode, keywords: ["scan", "retail"] },
    ],
  },
  {
    id: "business",
    label: msg`Business & finance`,
    icons: [
      { id: "briefcase", Icon: Briefcase, keywords: ["work", "job"] },
      { id: "trending-up", Icon: TrendingUp, keywords: ["growth", "analytics"] },
      { id: "bar-chart", Icon: BarChart3, keywords: ["analytics", "stats"] },
      { id: "line-chart", Icon: LineChart, keywords: ["analytics", "stats"] },
      { id: "pie-chart", Icon: PieChart, keywords: ["analytics", "stats"] },
      { id: "gauge", Icon: GaugeCircle, keywords: ["metrics", "speed"] },
      { id: "wallet", Icon: Wallet, keywords: ["money", "pay"] },
      { id: "wallet-cards", Icon: WalletCards, keywords: ["money", "pay"] },
      { id: "credit-card", Icon: CreditCard, keywords: ["payment", "billing"] },
      { id: "piggy-bank", Icon: PiggyBank, keywords: ["savings"] },
      { id: "bitcoin", Icon: Bitcoin, keywords: ["crypto", "currency"] },
      { id: "landmark", Icon: Landmark, keywords: ["bank", "institution"] },
      { id: "store", Icon: Store, keywords: ["shop", "retail"] },
      { id: "shopping-cart", Icon: ShoppingCart, keywords: ["ecommerce", "cart"] },
      { id: "shopping-bag", Icon: ShoppingBag, keywords: ["ecommerce", "shop"] },
      { id: "package", Icon: Package, keywords: ["box", "shipping", "npm"] },
      { id: "boxes", Icon: Boxes, keywords: ["inventory", "packages"] },
      { id: "badge-check", Icon: BadgeCheck, keywords: ["verified", "quality"] },
      { id: "award", Icon: Award, keywords: ["prize", "quality"] },
      { id: "ribbon", Icon: Ribbon, keywords: ["prize", "badge"] },
      { id: "trophy", Icon: Trophy, keywords: ["win", "prize"] },
      { id: "medal", Icon: Medal, keywords: ["win", "prize"] },
      { id: "target", Icon: Target, keywords: ["goal", "bullseye"] },
      { id: "megaphone", Icon: Megaphone, keywords: ["announce", "marketing"] },
      { id: "contact", Icon: Contact, keywords: ["card", "person"] },
      { id: "users", Icon: Users, keywords: ["team", "people"] },
      { id: "user", Icon: UserRound, keywords: ["person", "profile"] },
      { id: "handshake", Icon: Handshake, keywords: ["deal", "agreement"] },
    ],
  },
  {
    id: "science",
    label: msg`Science & education`,
    icons: [
      { id: "graduation-cap", Icon: GraduationCap, keywords: ["university", "learn"] },
      { id: "school", Icon: School, keywords: ["university", "learn"] },
      { id: "flask", Icon: FlaskConical, keywords: ["lab", "experiment", "science"] },
      { id: "microscope", Icon: Microscope, keywords: ["lab", "research"] },
      { id: "atom", Icon: Atom, keywords: ["physics", "science"] },
      { id: "orbit", Icon: Orbit, keywords: ["space", "satellite"] },
      { id: "telescope", Icon: Telescope, keywords: ["space", "stars"] },
      { id: "satellite", Icon: Satellite, keywords: ["space", "gps"] },
      { id: "brain", Icon: Brain, keywords: ["ai", "ml", "smart"] },
      { id: "lightbulb", Icon: Lightbulb, keywords: ["idea", "tip"] },
      { id: "stethoscope", Icon: Stethoscope, keywords: ["health", "doctor"] },
      { id: "syringe", Icon: Syringe, keywords: ["health", "vaccine"] },
      { id: "pill", Icon: Pill, keywords: ["health", "medicine"] },
      { id: "heart-pulse", Icon: HeartPulse, keywords: ["health", "fitness"] },
      { id: "activity", Icon: Activity, keywords: ["pulse", "metrics", "health"] },
      { id: "dumbbell", Icon: Dumbbell, keywords: ["gym", "fitness"] },
      { id: "biohazard", Icon: Biohazard, keywords: ["danger", "lab"] },
      { id: "radiation", Icon: Radiation, keywords: ["danger", "nuclear"] },
      { id: "recycle", Icon: Recycle, keywords: ["green", "eco"] },
    ],
  },
  {
    id: "food",
    label: msg`Food & drink`,
    icons: [
      { id: "coffee", Icon: Coffee, keywords: ["cafe", "espresso"] },
      { id: "pizza", Icon: Pizza, keywords: ["food"] },
      { id: "cake", Icon: Cake, keywords: ["birthday", "dessert"] },
      { id: "cookie", Icon: Cookie, keywords: ["biscuit", "dessert"] },
      { id: "donut", Icon: Donut, keywords: ["doughnut", "dessert"] },
      { id: "ice-cream", Icon: IceCreamCone, keywords: ["dessert"] },
      { id: "sandwich", Icon: Sandwich, keywords: ["food", "lunch"] },
      { id: "soup", Icon: Soup, keywords: ["food", "bowl"] },
      { id: "salad", Icon: Salad, keywords: ["food", "healthy"] },
      { id: "utensils", Icon: Utensils, keywords: ["restaurant", "food"] },
      { id: "chef-hat", Icon: ChefHat, keywords: ["restaurant", "cook"] },
      { id: "apple", Icon: Apple, keywords: ["fruit", "mac"] },
      { id: "banana", Icon: Banana, keywords: ["fruit"] },
      { id: "cherry", Icon: Cherry, keywords: ["fruit"] },
      { id: "grape", Icon: Grape, keywords: ["fruit", "wine"] },
      { id: "beer", Icon: Beer, keywords: ["drink", "bar"] },
      { id: "wine", Icon: Wine, keywords: ["drink", "bar"] },
      { id: "martini", Icon: Martini, keywords: ["drink", "cocktail"] },
      { id: "cup-soda", Icon: CupSoda, keywords: ["drink", "softdrink"] },
    ],
  },
  {
    id: "nature",
    label: msg`Nature & weather`,
    icons: [
      { id: "leaf", Icon: Leaf, keywords: ["green", "eco", "plant"] },
      { id: "tree-pine", Icon: TreePine, keywords: ["forest", "plant"] },
      { id: "flower", Icon: Flower2, keywords: ["plant", "bloom"] },
      { id: "palmtree", Icon: Palmtree, keywords: ["tropical", "beach"] },
      { id: "mountain", Icon: Mountain, keywords: ["hike", "outdoors"] },
      { id: "waves", Icon: Waves, keywords: ["sea", "ocean"] },
      { id: "droplets", Icon: Droplets, keywords: ["water"] },
      { id: "sun", Icon: Sun, keywords: ["light", "day"] },
      { id: "moon", Icon: Moon, keywords: ["night", "dark"] },
      { id: "moon-star", Icon: MoonStar, keywords: ["night"] },
      { id: "star", Icon: Star, keywords: ["favorite"] },
      { id: "sparkles", Icon: Sparkles, keywords: ["magic", "ai", "new"] },
      { id: "rainbow", Icon: Rainbow, keywords: ["colors", "pride"] },
      { id: "cloud", Icon: Cloud, keywords: ["weather"] },
      { id: "cloud-rain", Icon: CloudRain, keywords: ["weather"] },
      { id: "cloud-snow", Icon: CloudSnow, keywords: ["weather", "winter"] },
      { id: "cloud-lightning", Icon: CloudLightning, keywords: ["weather", "storm"] },
      { id: "snowflake", Icon: Snowflake, keywords: ["winter", "cold"] },
      { id: "wind", Icon: Wind, keywords: ["weather", "air"] },
      { id: "tornado", Icon: Tornado, keywords: ["weather", "storm"] },
      { id: "umbrella", Icon: Umbrella, keywords: ["rain"] },
      { id: "sunrise", Icon: Sunrise, keywords: ["morning"] },
      { id: "sunset", Icon: Sunset, keywords: ["evening"] },
      { id: "earth", Icon: Earth, keywords: ["world", "globe", "planet"] },
      { id: "earth-lock", Icon: EarthLock, keywords: ["private", "world"] },
      { id: "globe", Icon: Globe, keywords: ["world", "web", "internet"] },
      { id: "globe-2", Icon: Globe2, keywords: ["world", "web"] },
      { id: "globe-lock", Icon: GlobeLock, keywords: ["private", "web"] },
      { id: "paw-print", Icon: PawPrint, keywords: ["pet", "animal"] },
      { id: "cat", Icon: Cat, keywords: ["pet", "animal"] },
      { id: "dog", Icon: Dog, keywords: ["pet", "animal"] },
      { id: "bird", Icon: Bird, keywords: ["animal"] },
      { id: "fish", Icon: Fish, keywords: ["animal", "sea"] },
      { id: "snail", Icon: Snail, keywords: ["slow", "animal"] },
      { id: "shell", Icon: Shell, keywords: ["sea", "beach"] },
    ],
  },
  {
    id: "travel",
    label: msg`Travel & places`,
    icons: [
      { id: "plane", Icon: Plane, keywords: ["travel", "flight"] },
      { id: "car", Icon: Car, keywords: ["vehicle", "drive"] },
      { id: "car-front", Icon: CarFront, keywords: ["vehicle", "drive"] },
      { id: "bike", Icon: Bike, keywords: ["bicycle", "cycle"] },
      { id: "ship", Icon: Ship, keywords: ["boat", "sea"] },
      { id: "sailboat", Icon: Sailboat, keywords: ["boat", "sea"] },
      { id: "train", Icon: TrainFront, keywords: ["railway"] },
      { id: "bus", Icon: Bus, keywords: ["transit"] },
      { id: "truck", Icon: Truck, keywords: ["delivery", "logistics"] },
      { id: "tractor", Icon: Tractor, keywords: ["farm", "agriculture"] },
      { id: "ambulance", Icon: Ambulance, keywords: ["emergency", "health"] },
      { id: "compass", Icon: Compass, keywords: ["explore", "direction"] },
      { id: "navigation", Icon: Navigation, keywords: ["gps", "direction"] },
      { id: "map", Icon: MapIcon, keywords: ["location"] },
      { id: "map-pinned", Icon: MapPinned, keywords: ["location", "place"] },
      { id: "route", Icon: Route, keywords: ["path", "directions"] },
      { id: "waypoints", Icon: Waypoints, keywords: ["route", "stops"] },
      { id: "signpost", Icon: Signpost, keywords: ["directions"] },
      { id: "milestone", Icon: Milestone, keywords: ["version", "release"] },
      { id: "anchor", Icon: Anchor, keywords: ["sea", "harbor"] },
      { id: "tent", Icon: Tent, keywords: ["camping", "outdoors"] },
      { id: "castle", Icon: Castle, keywords: ["building", "medieval"] },
      { id: "church", Icon: Church, keywords: ["building"] },
      { id: "hospital", Icon: Hospital, keywords: ["health", "building"] },
      { id: "building", Icon: Building2, keywords: ["office", "city"] },
      { id: "factory", Icon: Factory, keywords: ["industry", "manufacturing"] },
      { id: "house", Icon: House, keywords: ["home"] },
      { id: "tower-control", Icon: TowerControl, keywords: ["airport"] },
      { id: "ferris-wheel", Icon: FerrisWheel, keywords: ["park", "fun"] },
    ],
  },
  {
    id: "games",
    label: msg`Games & fun`,
    icons: [
      { id: "gamepad", Icon: Gamepad2, keywords: ["gaming", "controller"] },
      { id: "joystick", Icon: Joystick, keywords: ["gaming", "arcade"] },
      { id: "puzzle", Icon: Puzzle, keywords: ["extension", "plugin", "piece"] },
      { id: "toy-brick", Icon: ToyBrick, keywords: ["lego", "blocks"] },
      { id: "dice", Icon: Dice5, keywords: ["random", "chance"] },
      { id: "ghost", Icon: Ghost, keywords: ["spooky", "halloween"] },
      { id: "skull", Icon: Skull, keywords: ["danger", "spooky"] },
      { id: "space", Icon: Space, keywords: ["galaxy", "universe"] },
      { id: "party-popper", Icon: PartyPopper, keywords: ["celebration", "release"] },
      { id: "balloon", Icon: Balloon, keywords: ["celebration"] },
      { id: "gift", Icon: Gift, keywords: ["present"] },
      { id: "crown", Icon: Crown, keywords: ["premium", "king"] },
      { id: "gem", Icon: Gem, keywords: ["diamond", "premium"] },
      { id: "sparkle", Icon: Sparkle, keywords: ["magic", "new"] },
      { id: "wand", Icon: Wand, keywords: ["magic"] },
      { id: "wand-sparkles", Icon: WandSparkles, keywords: ["magic", "ai"] },
      { id: "swords", Icon: Swords, keywords: ["battle", "gaming"] },
      { id: "crosshair", Icon: Crosshair, keywords: ["fps", "aim"] },
      { id: "rocket", Icon: Rocket, keywords: ["launch", "startup", "deploy"] },
      { id: "zap", Icon: Zap, keywords: ["lightning", "fast", "power"] },
      { id: "flame", Icon: Flame, keywords: ["fire", "hot", "lit"] },
    ],
  },
  {
    id: "communication",
    label: msg`Communication`,
    icons: [
      { id: "message-circle", Icon: MessageCircle, keywords: ["chat", "comment"] },
      { id: "messages-square", Icon: MessagesSquare, keywords: ["chat", "comments"] },
      { id: "mail", Icon: Mail, keywords: ["email", "inbox"] },
      { id: "send", Icon: Send, keywords: ["share", "paper plane"] },
      { id: "inbox", Icon: Inbox, keywords: ["email"] },
      { id: "phone", Icon: Phone, keywords: ["call"] },
      { id: "bell", Icon: Bell, keywords: ["notification", "alert"] },
      { id: "rss", Icon: Rss, keywords: ["feed", "blog"] },
      { id: "signal", Icon: Signal, keywords: ["connection"] },
      { id: "signal-high", Icon: SignalHigh, keywords: ["connection"] },
      { id: "antenna", Icon: Antenna, keywords: ["signal", "broadcast"] },
      { id: "wifi", Icon: Wifi, keywords: ["wireless", "internet"] },
      { id: "bluetooth", Icon: Bluetooth, keywords: ["wireless"] },
      { id: "nfc", Icon: Nfc, keywords: ["contactless", "tap"] },
      { id: "heart", Icon: Heart, keywords: ["love", "favorite"] },
      { id: "heart-handshake", Icon: HeartHandshake, keywords: ["care", "charity"] },
    ],
  },
  {
    id: "devices",
    label: msg`Devices & tools`,
    icons: [
      { id: "smartphone", Icon: Smartphone, keywords: ["mobile", "phone"] },
      { id: "laptop", Icon: Laptop, keywords: ["computer", "notebook"] },
      { id: "monitor", Icon: Monitor, keywords: ["desktop", "screen"] },
      { id: "keyboard", Icon: Keyboard, keywords: ["input", "typing"] },
      { id: "mouse", Icon: Mouse, keywords: ["input", "pointer"] },
      { id: "printer", Icon: Printer, keywords: ["print"] },
      { id: "hard-drive", Icon: HardDrive, keywords: ["disk", "storage"] },
      { id: "memory-stick", Icon: MemoryStick, keywords: ["ram", "storage"] },
      { id: "usb", Icon: Usb, keywords: ["port", "drive"] },
      { id: "cable", Icon: Cable, keywords: ["wire", "plug"] },
      { id: "plug", Icon: Plug, keywords: ["power", "connection"] },
      { id: "plug-2", Icon: Plug2, keywords: ["power", "connection"] },
      { id: "plug-zap", Icon: PlugZap, keywords: ["power", "charging"] },
      { id: "battery", Icon: Battery, keywords: ["power"] },
      { id: "battery-charging", Icon: BatteryCharging, keywords: ["power"] },
      { id: "fan", Icon: Fan, keywords: ["cooling"] },
      { id: "thermometer", Icon: Thermometer, keywords: ["temperature"] },
      { id: "magnet", Icon: Magnet, keywords: ["attract"] },
      { id: "flashlight", Icon: Flashlight, keywords: ["torch", "light"] },
      { id: "key", Icon: KeyRound, keywords: ["password", "secret"] },
      { id: "lock", Icon: Lock, keywords: ["secure", "private"] },
      { id: "shield", Icon: Shield, keywords: ["security", "defense"] },
      { id: "shield-check", Icon: ShieldCheck, keywords: ["security", "verified"] },
      { id: "fingerprint", Icon: Fingerprint, keywords: ["biometric", "identity"] },
      { id: "watch", Icon: Watch, keywords: ["time", "wearable"] },
      { id: "alarm-clock", Icon: AlarmClock, keywords: ["time", "reminder"] },
      { id: "hourglass", Icon: Hourglass, keywords: ["time", "waiting"] },
      { id: "timer", Icon: Timer, keywords: ["time", "countdown"] },
      { id: "clock", Icon: Clock, keywords: ["time", "schedule"] },
      { id: "calendar", Icon: Calendar, keywords: ["date", "schedule"] },
      { id: "scissors", Icon: Scissors, keywords: ["cut", "tool"] },
      { id: "ruler", Icon: Ruler, keywords: ["measure", "tool"] },
      { id: "eraser", Icon: Eraser, keywords: ["clear", "tool"] },
      { id: "paperclip", Icon: Paperclip, keywords: ["attachment"] },
      { id: "bookmark", Icon: Bookmark, keywords: ["save", "favorite"] },
      { id: "eye", Icon: Eye, keywords: ["view", "visible"] },
      { id: "glasses", Icon: Glasses, keywords: ["vision", "read"] },
      { id: "ear", Icon: Ear, keywords: ["hear", "audio"] },
      { id: "baby", Icon: Baby, keywords: ["child", "new"] },
      { id: "accessibility", Icon: Accessibility, keywords: ["a11y"] },
      { id: "panel-left", Icon: PanelLeft, keywords: ["sidebar", "layout"] },
      { id: "armchair", Icon: Armchair, keywords: ["furniture", "home"] },
      { id: "bed-double", Icon: BedDouble, keywords: ["furniture", "home"] },
      { id: "bath", Icon: Bath, keywords: ["home", "spa"] },
      { id: "lamp", Icon: Lamp, keywords: ["light", "home"] },
      { id: "lamp-desk", Icon: LampDesk, keywords: ["light", "work"] },
    ],
  },
  {
    id: "shapes",
    label: msg`Shapes & symbols`,
    icons: [
      { id: "circle", Icon: Circle, keywords: ["shape", "dot"] },
      { id: "square", Icon: Square, keywords: ["shape", "box"] },
      { id: "triangle", Icon: Triangle, keywords: ["shape"] },
      { id: "hexagon", Icon: Hexagon, keywords: ["shape", "node"] },
      { id: "pentagon", Icon: Pentagon, keywords: ["shape"] },
      { id: "octagon", Icon: Octagon, keywords: ["shape", "stop"] },
    ],
  },
];

export const PROJECT_ICONS: readonly ProjectIconEntry[] = PROJECT_ICON_CATEGORIES.flatMap(
  (category) => category.icons,
);

const projectIconIndex = new Map<string, ProjectIconEntry>(
  PROJECT_ICONS.map((entry) => [entry.id, entry]),
);

const projectIconCategoryIndex = new Map<string, ProjectIconCategory>(
  PROJECT_ICON_CATEGORIES.flatMap((category) =>
    category.icons.map((entry) => [entry.id, category] as const),
  ),
);

export function findProjectIcon(id: string): ProjectIconEntry | undefined {
  return projectIconIndex.get(id);
}

/** The category a glyph belongs to — search results lose that grouping. */
export function findProjectIconCategory(id: string): ProjectIconCategory | undefined {
  return projectIconCategoryIndex.get(id);
}

/** Human-readable label for a catalog id: `folder-git` → `Folder Git`. */
export function projectIconDisplayName(id: string): string {
  return id
    .split("-")
    .map((word) => (word ? word[0]!.toUpperCase() + word.slice(1) : word))
    .join(" ");
}

/** Lowercased id + keywords per entry, built once so search never re-joins. */
const projectIconSearchTerms = new Map<string, string>(
  PROJECT_ICONS.map((entry) => [
    entry.id,
    (entry.keywords ? `${entry.id} ${entry.keywords.join(" ")}` : entry.id).toLowerCase(),
  ]),
);

/** Case-insensitive substring search across ids and keywords. */
export function searchProjectIcons(query: string): readonly ProjectIconEntry[] {
  const trimmed = query.trim().toLowerCase();
  if (!trimmed) return PROJECT_ICONS;
  const terms = trimmed.split(/\s+/);
  return PROJECT_ICONS.filter((entry) => {
    const haystack = projectIconSearchTerms.get(entry.id) ?? entry.id;
    return terms.every((term) => haystack.includes(term));
  });
}
