import {
  createFileCheckpointPayloadSchema,
  finalizeFileCheckpointPayloadSchema,
  generateCommitMessagePayloadSchema,
  generatePrSummaryPayloadSchema,
  generateTitlePayloadSchema,
  getGitBranchesPayloadSchema,
  getGitDiffBatchPayloadSchema,
  getGitDiffPayloadSchema,
  getGitFileContentPayloadSchema,
  getGitStatusPayloadSchema,
  gitAbortMergePayloadSchema,
  gitAddRemotePayloadSchema,
  gitAddWorktreePayloadSchema,
  gitCommitPayloadSchema,
  gitDeleteBranchPayloadSchema,
  gitFetchPayloadSchema,
  gitFinishMergePayloadSchema,
  gitGetWorktreeOwnerPayloadSchema,
  gitGetWorktreeSourceBranchPayloadSchema,
  gitInitPayloadSchema,
  gitListWorktreesPayloadSchema,
  gitMergeToSourcePayloadSchema,
  gitProjectSnapshotPayloadSchema,
  gitPullFromSourcePayloadSchema,
  gitPullPayloadSchema,
  gitPruneWorktreesPayloadSchema,
  gitPushPayloadSchema,
  gitRemoveWorktreePayloadSchema,
  gitRevertAllPayloadSchema,
  gitRevertPayloadSchema,
  gitStageAllPayloadSchema,
  gitStagePayloadSchema,
  gitSwitchBranchPayloadSchema,
  gitSyncPayloadSchema,
  gitUnstageAllPayloadSchema,
  gitUnstagePayloadSchema,
  gitUnwatchProjectPayloadSchema,
  gitWatchProjectPayloadSchema,
  gitWatchWorktreesPayloadSchema,
  gitWorktreeStatusBatchPayloadSchema,
  listFileCheckpointsPayloadSchema,
  relocateProjectPayloadSchema,
  restoreFileCheckpointPayloadSchema,
  createFileCheckpointResultSchema,
  finalizeFileCheckpointResultSchema,
  generateCommitMessageResultSchema,
  generatePrSummaryResultSchema,
  generateTitleResultSchema,
  gitAbortMergeResultSchema,
  gitAddWorktreeResultSchema,
  gitBranchListResultSchema,
  gitCommitResultSchema,
  gitDiffBatchResultSchema,
  gitDiffResultSchema,
  gitFileContentResultSchema,
  gitFinishMergeResultSchema,
  gitGetWorktreeOwnerResultSchema,
  gitGetWorktreeSourceBranchResultSchema,
  gitMergeToSourceResultSchema,
  gitProjectSnapshotResultSchema,
  gitPullFromSourceResultSchema,
  gitStatusResultSchema,
  gitSwitchBranchResultSchema,
  gitSyncResultSchema,
  gitWorktreeListResultSchema,
  gitWorktreeStatusBatchResultSchema,
  listFileCheckpointsResultSchema,
} from "../../contracts";
import type {
  CreateFileCheckpointPayload,
  CreateFileCheckpointResult,
  FinalizeFileCheckpointPayload,
  FinalizeFileCheckpointResult,
  GenerateCommitMessagePayload,
  GenerateCommitMessageResult,
  GeneratePrSummaryPayload,
  GeneratePrSummaryResult,
  GenerateTitlePayload,
  GenerateTitleResult,
  GetGitBranchesPayload,
  GetGitDiffBatchPayload,
  GetGitDiffPayload,
  GetGitFileContentPayload,
  GetGitStatusPayload,
  GitAbortMergePayload,
  GitAbortMergeResult,
  GitAddRemotePayload,
  GitAddWorktreePayload,
  GitAddWorktreeResult,
  GitBranchListResult,
  GitCommitPayload,
  GitCommitResult,
  GitDeleteBranchPayload,
  GitDiffBatchResult,
  GitDiffResult,
  GitFetchPayload,
  GitFileContentResult,
  GitFinishMergePayload,
  GitFinishMergeResult,
  GitGetWorktreeOwnerPayload,
  GitGetWorktreeOwnerResult,
  GitGetWorktreeSourceBranchPayload,
  GitGetWorktreeSourceBranchResult,
  GitInitPayload,
  GitListWorktreesPayload,
  GitMergeToSourcePayload,
  GitMergeToSourceResult,
  GitProjectSnapshotPayload,
  GitProjectSnapshotResult,
  GitPullFromSourcePayload,
  GitPullFromSourceResult,
  GitPullPayload,
  GitPruneWorktreesPayload,
  GitPushPayload,
  GitRemoveWorktreePayload,
  GitRevertAllPayload,
  GitRevertPayload,
  GitStageAllPayload,
  GitStagePayload,
  GitStatusResult,
  GitSwitchBranchPayload,
  GitSwitchBranchResult,
  GitSyncPayload,
  GitSyncResult,
  GitUnstageAllPayload,
  GitUnstagePayload,
  GitUnwatchProjectPayload,
  GitWatchProjectPayload,
  GitWatchWorktreesPayload,
  GitWorktreeListResult,
  GitWorktreeStatusBatchPayload,
  GitWorktreeStatusBatchResult,
  ListFileCheckpointsPayload,
  ListFileCheckpointsResult,
  RelocateProjectPayload,
  RelocateProjectResult,
  RestoreFileCheckpointPayload,
} from "../../contracts";
import { definePayloadProcedure, omittedResultSchema } from "../core";

export const gitProcedures = {
  createFileCheckpoint: definePayloadProcedure<
    CreateFileCheckpointPayload,
    CreateFileCheckpointResult,
    "supervisor"
  >(
    "createFileCheckpoint",
    "supervisor",
    createFileCheckpointPayloadSchema,
    createFileCheckpointResultSchema,
  ),
  finalizeFileCheckpoint: definePayloadProcedure<
    FinalizeFileCheckpointPayload,
    FinalizeFileCheckpointResult,
    "supervisor"
  >(
    "finalizeFileCheckpoint",
    "supervisor",
    finalizeFileCheckpointPayloadSchema,
    finalizeFileCheckpointResultSchema,
  ),
  listFileCheckpoints: definePayloadProcedure<
    ListFileCheckpointsPayload,
    ListFileCheckpointsResult,
    "supervisor"
  >(
    "listFileCheckpoints",
    "supervisor",
    listFileCheckpointsPayloadSchema,
    listFileCheckpointsResultSchema,
  ),
  restoreFileCheckpoint: definePayloadProcedure<RestoreFileCheckpointPayload, void, "supervisor">(
    "restoreFileCheckpoint",
    "supervisor",
    restoreFileCheckpointPayloadSchema,
    omittedResultSchema,
  ),
  getGitStatus: definePayloadProcedure<GetGitStatusPayload, GitStatusResult, "supervisor">(
    "getGitStatus",
    "supervisor",
    getGitStatusPayloadSchema,
    gitStatusResultSchema,
  ),
  getGitDiff: definePayloadProcedure<GetGitDiffPayload, GitDiffResult, "supervisor">(
    "getGitDiff",
    "supervisor",
    getGitDiffPayloadSchema,
    gitDiffResultSchema,
  ),
  getGitDiffBatch: definePayloadProcedure<GetGitDiffBatchPayload, GitDiffBatchResult, "supervisor">(
    "getGitDiffBatch",
    "supervisor",
    getGitDiffBatchPayloadSchema,
    gitDiffBatchResultSchema,
  ),
  getGitFileContent: definePayloadProcedure<
    GetGitFileContentPayload,
    GitFileContentResult,
    "supervisor"
  >("getGitFileContent", "supervisor", getGitFileContentPayloadSchema, gitFileContentResultSchema),
  gitStage: definePayloadProcedure<GitStagePayload, void, "supervisor">(
    "gitStage",
    "supervisor",
    gitStagePayloadSchema,
    omittedResultSchema,
  ),
  gitUnstage: definePayloadProcedure<GitUnstagePayload, void, "supervisor">(
    "gitUnstage",
    "supervisor",
    gitUnstagePayloadSchema,
    omittedResultSchema,
  ),
  gitRevert: definePayloadProcedure<GitRevertPayload, void, "supervisor">(
    "gitRevert",
    "supervisor",
    gitRevertPayloadSchema,
    omittedResultSchema,
  ),
  gitStageAll: definePayloadProcedure<GitStageAllPayload, void, "supervisor">(
    "gitStageAll",
    "supervisor",
    gitStageAllPayloadSchema,
    omittedResultSchema,
  ),
  gitUnstageAll: definePayloadProcedure<GitUnstageAllPayload, void, "supervisor">(
    "gitUnstageAll",
    "supervisor",
    gitUnstageAllPayloadSchema,
    omittedResultSchema,
  ),
  gitRevertAll: definePayloadProcedure<GitRevertAllPayload, void, "supervisor">(
    "gitRevertAll",
    "supervisor",
    gitRevertAllPayloadSchema,
    omittedResultSchema,
  ),
  gitCommit: definePayloadProcedure<GitCommitPayload, GitCommitResult, "supervisor">(
    "gitCommit",
    "supervisor",
    gitCommitPayloadSchema,
    gitCommitResultSchema,
  ),
  gitInit: definePayloadProcedure<GitInitPayload, void, "supervisor">(
    "gitInit",
    "supervisor",
    gitInitPayloadSchema,
    omittedResultSchema,
  ),
  gitAddRemote: definePayloadProcedure<GitAddRemotePayload, void, "supervisor">(
    "gitAddRemote",
    "supervisor",
    gitAddRemotePayloadSchema,
    omittedResultSchema,
  ),
  generateCommitMessage: definePayloadProcedure<
    GenerateCommitMessagePayload,
    GenerateCommitMessageResult,
    "supervisor"
  >(
    "generateCommitMessage",
    "supervisor",
    generateCommitMessagePayloadSchema,
    generateCommitMessageResultSchema,
  ),
  generateTitle: definePayloadProcedure<GenerateTitlePayload, GenerateTitleResult, "supervisor">(
    "generateTitle",
    "supervisor",
    generateTitlePayloadSchema,
    generateTitleResultSchema,
  ),
  generatePrSummary: definePayloadProcedure<
    GeneratePrSummaryPayload,
    GeneratePrSummaryResult,
    "supervisor"
  >(
    "generatePrSummary",
    "supervisor",
    generatePrSummaryPayloadSchema,
    generatePrSummaryResultSchema,
  ),
  gitListBranches: definePayloadProcedure<GetGitBranchesPayload, GitBranchListResult, "supervisor">(
    "gitListBranches",
    "supervisor",
    getGitBranchesPayloadSchema,
    gitBranchListResultSchema,
  ),
  gitFetch: definePayloadProcedure<GitFetchPayload, void, "supervisor">(
    "gitFetch",
    "supervisor",
    gitFetchPayloadSchema,
    omittedResultSchema,
  ),
  gitListWorktrees: definePayloadProcedure<
    GitListWorktreesPayload,
    GitWorktreeListResult,
    "supervisor"
  >("gitListWorktrees", "supervisor", gitListWorktreesPayloadSchema, gitWorktreeListResultSchema),
  gitAddWorktree: definePayloadProcedure<GitAddWorktreePayload, GitAddWorktreeResult, "supervisor">(
    "gitAddWorktree",
    "supervisor",
    gitAddWorktreePayloadSchema,
    gitAddWorktreeResultSchema,
  ),
  gitRemoveWorktree: definePayloadProcedure<GitRemoveWorktreePayload, void, "supervisor">(
    "gitRemoveWorktree",
    "supervisor",
    gitRemoveWorktreePayloadSchema,
    omittedResultSchema,
  ),
  gitPruneWorktrees: definePayloadProcedure<GitPruneWorktreesPayload, void, "supervisor">(
    "gitPruneWorktrees",
    "supervisor",
    gitPruneWorktreesPayloadSchema,
    omittedResultSchema,
  ),
  gitDeleteBranch: definePayloadProcedure<GitDeleteBranchPayload, void, "supervisor">(
    "gitDeleteBranch",
    "supervisor",
    gitDeleteBranchPayloadSchema,
    omittedResultSchema,
  ),
  gitSwitchBranch: definePayloadProcedure<
    GitSwitchBranchPayload,
    GitSwitchBranchResult,
    "supervisor"
  >("gitSwitchBranch", "supervisor", gitSwitchBranchPayloadSchema, gitSwitchBranchResultSchema),
  gitPull: definePayloadProcedure<GitPullPayload, void, "supervisor">(
    "gitPull",
    "supervisor",
    gitPullPayloadSchema,
    omittedResultSchema,
  ),
  gitPullRebase: definePayloadProcedure<GitPullPayload, void, "supervisor">(
    "gitPullRebase",
    "supervisor",
    gitPullPayloadSchema,
    omittedResultSchema,
  ),
  gitPush: definePayloadProcedure<GitPushPayload, void, "supervisor">(
    "gitPush",
    "supervisor",
    gitPushPayloadSchema,
    omittedResultSchema,
  ),
  gitSync: definePayloadProcedure<GitSyncPayload, GitSyncResult, "supervisor">(
    "gitSync",
    "supervisor",
    gitSyncPayloadSchema,
    gitSyncResultSchema,
  ),
  gitSyncRebase: definePayloadProcedure<GitSyncPayload, GitSyncResult, "supervisor">(
    "gitSyncRebase",
    "supervisor",
    gitSyncPayloadSchema,
    gitSyncResultSchema,
  ),
  gitProjectSnapshot: definePayloadProcedure<
    GitProjectSnapshotPayload,
    GitProjectSnapshotResult,
    "supervisor"
  >(
    "gitProjectSnapshot",
    "supervisor",
    gitProjectSnapshotPayloadSchema,
    gitProjectSnapshotResultSchema,
  ),
  gitWorktreeStatusBatch: definePayloadProcedure<
    GitWorktreeStatusBatchPayload,
    GitWorktreeStatusBatchResult,
    "supervisor"
  >(
    "gitWorktreeStatusBatch",
    "supervisor",
    gitWorktreeStatusBatchPayloadSchema,
    gitWorktreeStatusBatchResultSchema,
  ),
  gitGetWorktreeSourceBranch: definePayloadProcedure<
    GitGetWorktreeSourceBranchPayload,
    GitGetWorktreeSourceBranchResult,
    "supervisor"
  >(
    "gitGetWorktreeSourceBranch",
    "supervisor",
    gitGetWorktreeSourceBranchPayloadSchema,
    gitGetWorktreeSourceBranchResultSchema,
  ),
  gitGetWorktreeOwner: definePayloadProcedure<
    GitGetWorktreeOwnerPayload,
    GitGetWorktreeOwnerResult,
    "supervisor"
  >(
    "gitGetWorktreeOwner",
    "supervisor",
    gitGetWorktreeOwnerPayloadSchema,
    gitGetWorktreeOwnerResultSchema,
  ),
  gitMergeToSource: definePayloadProcedure<
    GitMergeToSourcePayload,
    GitMergeToSourceResult,
    "supervisor"
  >("gitMergeToSource", "supervisor", gitMergeToSourcePayloadSchema, gitMergeToSourceResultSchema),
  gitPullFromSource: definePayloadProcedure<
    GitPullFromSourcePayload,
    GitPullFromSourceResult,
    "supervisor"
  >(
    "gitPullFromSource",
    "supervisor",
    gitPullFromSourcePayloadSchema,
    gitPullFromSourceResultSchema,
  ),
  gitAbortMerge: definePayloadProcedure<GitAbortMergePayload, GitAbortMergeResult, "supervisor">(
    "gitAbortMerge",
    "supervisor",
    gitAbortMergePayloadSchema,
    gitAbortMergeResultSchema,
  ),
  gitFinishMerge: definePayloadProcedure<GitFinishMergePayload, GitFinishMergeResult, "supervisor">(
    "gitFinishMerge",
    "supervisor",
    gitFinishMergePayloadSchema,
    gitFinishMergeResultSchema,
  ),
  gitWatchProject: definePayloadProcedure<GitWatchProjectPayload, void, "supervisor">(
    "gitWatchProject",
    "supervisor",
    gitWatchProjectPayloadSchema,
  ),
  gitWatchWorktrees: definePayloadProcedure<GitWatchWorktreesPayload, void, "supervisor">(
    "gitWatchWorktrees",
    "supervisor",
    gitWatchWorktreesPayloadSchema,
  ),
  gitUnwatchProject: definePayloadProcedure<GitUnwatchProjectPayload, void, "supervisor">(
    "gitUnwatchProject",
    "supervisor",
    gitUnwatchProjectPayloadSchema,
  ),
  relocateProject: definePayloadProcedure<
    RelocateProjectPayload,
    RelocateProjectResult,
    "supervisor"
  >("relocateProject", "supervisor", relocateProjectPayloadSchema),
} as const;
