/**
 * Markdown rendering of the E1/E3 inventory.
 *
 * Turns an inventory object into the human-readable evidence document. Pure
 * formatting: no filesystem access and no graph decisions.
 */

function mdList(items, empty = "_none_") {
  return items.length === 0 ? empty : items.map((item) => `- ${item}`).join("\n");
}

export function renderInventoryMarkdown(inventory) {
  const { graph, audit, entries } = inventory;
  const violationLines = audit.violations.map((violation) => {
    const chain = violation.chain
      .map((hop) => `${hop.from}${hop.line ? `:${hop.line}` : ""} → ${hop.to}`)
      .join(" → ");
    return `\`${violation.severity}\` **${violation.from}:${violation.line ?? "?"}** → \`${violation.to}\` (${violation.targetClass})${violation.finalOwner ? ` owner: \`${violation.finalOwner}\`` : ""}\n  - chain: ${chain}`;
  });

  const batchSections = inventory.moveBatches.map((batch) => {
    const modules = batch.modules
      .map((entry) => {
        const details = [];
        if (entry.compatibilityRewrites.length > 0) {
          details.push(
            `compat-barrel rewrites: ${entry.compatibilityRewrites
              .map((rewrite) => `\`${rewrite.to}\` → \`${rewrite.suggestedOwner}\``)
              .join(", ")}`,
          );
        }
        if (entry.mainDependenciesToResolve.length > 0) {
          details.push(
            `main dependencies to resolve (move together or invert): ${entry.mainDependenciesToResolve
              .map((target) => `\`${target}\``)
              .join(", ")}`,
          );
        }
        if (entry.intraBatchDependencies.length > 0) {
          details.push(`intra-batch: ${entry.intraBatchDependencies.length}`);
        }
        return (
          `- \`${entry.module}\` — runtime consumers: ${entry.consumers.length}, type consumers: ${entry.typeConsumers.length}, tests: ${entry.testConsumers.length}` +
          (details.length > 0 ? `\n  - ${details.join("\n  - ")}` : "")
        );
      })
      .join("\n");
    return [
      `### ${batch.id} — ${batch.title}`,
      "",
      `- order: ${batch.order}`,
      `- destination: \`${batch.destination}\``,
      `- rationale: ${batch.rationale}`,
      `- module count: ${batch.modules.length}; distinct runtime consumers: ${batch.consumerCount}`,
      "",
      modules || "_no modules matched in this tree_",
      "",
      `Expected tests: ${batch.expectedTests.map((test) => `\`${test}\``).join(", ") || "_none detected_"}`,
    ].join("\n");
  });

  const unresolvedComputed = inventory.unresolved.filter(
    (entry) => entry.reason === "computed-specifier",
  );
  const unresolvedOther = inventory.unresolved.filter(
    (entry) => entry.reason !== "computed-specifier",
  );

  return [
    "# E1/E3 architecture import inventory",
    "",
    "Generated by `node scripts/architecture-imports.mjs inventory`. Temporary evidence for the",
    "V2 E1/E3 work; not an enforcement gate. No deletion is authorized by this document.",
    "",
    "## Reproducible commands",
    "",
    "```bash",
    "node scripts/architecture-imports.mjs audit --root .",
    "node --test scripts/architecture-imports.test.mjs",
    "node scripts/architecture-imports.mjs inventory --root . --out-dir tmp/v2-production",
    "node scripts/architecture-imports.mjs consumers src/main/supervisor/SupervisorClient.ts",
    "```",
    "",
    "## Current counts",
    "",
    `- files: ${graph.files}`,
    `- edges: ${graph.edges} (runtime ${graph.runtimeEdges}, type-only ${graph.typeOnlyEdges}, external ${graph.externalEdges})`,
    `- barrels: ${graph.barrels}; compatibility re-exports: ${graph.compatibilityReexports}`,
    `- unresolved computed specifiers: ${graph.unresolvedComputed}`,
    `- unresolved other: ${graph.unresolvedOther}`,
    `- warnings: ${graph.warnings}`,
    `- boundary findings: ${audit.violations.length} (hard ${audit.hardViolations}, migration ${audit.migrationEdges}, compat-reexport ${audit.compatReexportEdges})`,
    `- build entries: ${entries.entries.length}; manifest entries: ${entries.manifestNames.length}`,
    `- roots: plugin ${inventory.roots.plugin.length}, deploy references ${inventory.roots.deploy.length}, path references ${inventory.roots.reference.length}, tests ${inventory.roots.testCount}`,
    `- electron chains from build roots: ${inventory.electronChains.length}`,
    `- build-reachable files: ${inventory.reachability.buildReachable}; tool-reachable: ${inventory.reachability.toolReachable}; test-only files: ${inventory.reachability.testOnly}`,
    `- dynamic ambiguity present: ${unresolvedComputed.length > 0 ? "yes" : "no"}`,
    "",
    "## Boundary findings",
    "",
    mdList(violationLines),
    "",
    "## Electron chains",
    "",
    mdList(
      inventory.electronChains.map(
        (chain) =>
          `${chain.root}: ${chain.path.map((hop) => `${hop.from} → ${hop.to}`).join(" → ")}`,
      ),
    ),
    "",
    "## Compatibility re-exports",
    "",
    mdList(
      inventory.compatibilityReexports.map(
        (entry) =>
          `\`${entry.module}\` → \`${entry.finalOwner}\` (runtime consumers: ${entry.consumers.length}, type: ${entry.typeConsumers.length})`,
      ),
    ),
    "",
    "## Move batches",
    "",
    batchSections.join("\n\n"),
    "",
    "## Additional move candidates (E1 findings outside declared batches)",
    "",
    mdList(
      inventory.additionalMoveCandidates.map(
        (candidate) =>
          `\`${candidate.module}\` (${candidate.classification}) — consumers: ${candidate.consumers.map((consumer) => `\`${consumer}\``).join(", ")}`,
      ),
    ),
    "",
    "## Unused compatibility re-exports (deletion review; check package/public imports first)",
    "",
    mdList(
      inventory.unusedCompatibilityReexports.map(
        (entry) => `\`${entry.module}\` → \`${entry.finalOwner}\``,
      ),
    ),
    "",
    "## Possible deletions (evidence; never delete from this list alone)",
    "",
    mdList(
      inventory.deletionCandidates.map(
        (candidate) =>
          `\`${candidate.module}\` [${candidate.confidence}] — ${candidate.note} inbound runtime: ${candidate.evidence.inboundRuntime.length}, type-only: ${candidate.evidence.inboundTypeOnly.length}, tests: ${candidate.evidence.inboundTests.length}`,
      ),
    ),
    "",
    "## Unresolved dynamic specifiers",
    "",
    mdList(
      unresolvedComputed
        .slice(0, 60)
        .map((entry) => `\`${entry.from}:${entry.line}\` ${entry.kind} ${entry.raw ?? ""}`),
      unresolvedComputed.length > 60
        ? `_…and ${unresolvedComputed.length - 60} more in the JSON_`
        : "_none_",
    ),
    "",
    "## Other unresolved specifiers",
    "",
    mdList(
      unresolvedOther.map(
        (entry) =>
          `\`${entry.from}:${entry.line}\` ${entry.specifier ?? ""} (${entry.reason})` +
          (entry.generatedBy ? ` generated by \`${entry.generatedBy}\`` : ""),
      ),
    ),
    "",
    "## Warnings",
    "",
    mdList(inventory.warnings.map((warning) => `\`${warning.file}\` ${warning.reason}`)),
    "",
  ].join("\n");
}
