import { omittedResultSchema } from "../../../ipc/resultCodec";
import type { RemoteProcedureName } from "../../procedures";
import { REMOTE_PROCEDURE_CONTRACTS } from "../procedures";

const OMITTED = omittedResultSchema;

const gitStatus = {
  isRepo: true,
  branch: "main",
  tracking: "origin/main",
  hasRemote: true,
  remoteInfo: {
    url: "git@github.com:acme/app.git",
    platform: "github" as const,
    owner: "acme",
    repo: "app",
  },
  ahead: 0,
  behind: 1,
  staged: [],
  unstaged: [{ path: "src/a.ts", status: "modified", staged: false, insertions: 2, deletions: 1 }],
  totalInsertions: 2,
  totalDeletions: 1,
};

const checkpoint = {
  threadId: "t1",
  checkpointItemId: "c1",
  ref: "refs/poracode/c1",
  commit: "abc",
  capturedAt: "2026-08-12T00:00:00.000Z",
};

const pr = {
  number: 12,
  state: "open" as const,
  title: "Ship remote contract",
  url: "https://github.com/acme/app/pull/12",
  baseBranch: "main",
  isDraft: false,
  updatedAt: "2026-08-12T00:00:00.000Z",
};

const workflowRun = {
  id: 9,
  workflowId: 1,
  workflowName: "ci",
  name: "CI",
  number: 3,
  attempt: 1,
  title: "CI",
  event: "push",
  headBranch: "main",
  headSha: "abc",
  status: "completed",
  conclusion: "success",
  createdAt: "2026-08-12T00:00:00.000Z",
  startedAt: "2026-08-12T00:00:00.000Z",
  updatedAt: "2026-08-12T00:00:00.000Z",
  url: "https://github.com/acme/app/actions/runs/9",
  jobs: [],
};

/**
 * One producer-shaped success value per remote procedure. Void procedures use
 * the shared omitted codec (`undefined` on the wire).
 */
export const REMOTE_PROCEDURE_RESULT_FIXTURES = {
  rollbackThreadConversation: undefined,
  createFileCheckpoint: { checkpoint },
  finalizeFileCheckpoint: {
    checkpoint: {
      ...checkpoint,
      baseCheckpointItemId: "c0",
      baseRef: "refs/poracode/c0",
      changedFiles: [],
    },
  },
  listFileCheckpoints: { checkpoints: [], turns: [] },
  restoreFileCheckpoint: undefined,
  subagentSubscribe: { history: [] },
  subagentUnsubscribe: undefined,
  stageThreadInput: undefined,
  workflowGetRun: { run: null },
  workflowAgentChat: { events: [] },
  scanSkills: {
    skills: [],
    effectiveSkillIds: [],
    invocation: null,
    issues: [],
    canLinkToGlobal: false,
  },
  listSkillMarketplace: { marketplace: "skills-sh", skills: [], total: 0 },
  setSkillEnabled: undefined,
  deleteSkill: undefined,
  importSkills: { imported: [] },
  installMarketplaceSkill: { installed: "/skills/demo" },
  discoverExternalMcpServers: { groups: [] },
  probeMcpServer: {
    status: "available",
    latencyMs: 12,
    environment: { runtime: "host", projectScoped: false },
    toolCount: 2,
  },
  getMcpOauthStatus: { authenticatedUrls: [] },
  beginMcpServerOauth: { status: "authorized" },
  waitMcpServerOauth: { status: "authorized" },
  clearMcpServerOauth: undefined,
  searchProjectFiles: { entries: [], totalIndexed: 0 },
  listProjectTree: { directoryPath: "", entries: [] },
  browseHostDirectory: {
    path: "/Users/dev",
    parentPath: "/Users",
    homePath: "/Users/dev",
    entries: [{ name: "src", path: "/Users/dev/src", type: "directory" }],
    truncated: false,
  },
  searchProjectTree: { entries: [] },
  readProjectFile: {
    path: "README.md",
    status: "ready",
    modifiedAtMs: 1.25,
    content: "# hi",
    lineEnding: "lf",
  },
  readAbsoluteFile: { status: "ready", modifiedAtMs: 1.25, content: "x" },
  readExternalFile: { path: "/tmp/a", status: "ready", modifiedAtMs: 1.25, content: "x" },
  writeProjectFile: { modifiedAtMs: 1.25 },
  writeExternalFile: { modifiedAtMs: 1.25 },
  createProjectEntry: undefined,
  renameProjectEntry: undefined,
  moveProjectEntry: undefined,
  deleteProjectEntry: undefined,
  detectSetupScript: {},
  getGitStatus: gitStatus,
  getGitDiff: { diff: "" },
  getGitDiffBatch: { staged: {}, unstaged: {} },
  getGitFileContent: { oldContent: "", newContent: "" },
  gitListBranches: { current: "main", branches: [] },
  gitListWorktrees: { worktrees: [] },
  gitProjectSnapshot: { status: null, branches: null, worktrees: null, ghAvailable: null },
  gitWorktreeStatusBatch: { statuses: {} },
  gitGetWorktreeSourceBranch: { sourceBranch: null, commitsAhead: 0, sourceAhead: 0 },
  gitGetWorktreeOwner: { ownerToken: null },
  ghCheckAvailable: { available: true },
  ghGetPrForBranch: null,
  ghListPrs: { prs: {} },
  ghListPullRequests: { pullRequests: [] },
  ghGetPrChecks: { checks: [] },
  ghGetPrFiles: { files: [] },
  ghGetPrDiff: { diff: "" },
  ghGetPrDetails: {
    details: {
      number: 12,
      title: "Ship",
      body: "",
      baseBranch: "main",
      headBranch: "feat",
      additions: 1,
      deletions: 0,
      changedFiles: 1,
      commits: [],
      comments: [],
      reviews: [],
      checks: [],
    },
  },
  ghGetPrReviewComments: { comments: [], threads: [] },
  ghListAccounts: { accounts: [] },
  ghListRepos: { repos: [] },
  ghListWorkflows: { workflows: [] },
  ghListWorkflowRuns: { runs: [] },
  ghGetWorkflowRun: { run: workflowRun },
  ghGetWorkflowDefinition: {
    definition: {
      workflowId: 1,
      ref: "main",
      defaultBranch: "main",
      dispatchable: true,
      triggers: ["workflow_dispatch"],
      inputs: [],
    },
  },
  gitStage: undefined,
  gitUnstage: undefined,
  gitRevert: undefined,
  gitStageAll: undefined,
  gitUnstageAll: undefined,
  gitRevertAll: undefined,
  gitCommit: { hash: "abc123", message: "fix: parse" },
  gitInit: undefined,
  gitAddRemote: undefined,
  generateCommitMessage: { message: "fix: parse" },
  generateTitle: { title: "Fix parse" },
  generatePrSummary: { title: "Fix parse", description: "body" },
  gitFetch: undefined,
  gitPull: undefined,
  gitPullRebase: undefined,
  gitPush: undefined,
  gitSync: { pulled: true, pushed: false },
  gitSyncRebase: { pulled: true, pushed: false },
  gitSwitchBranch: { branch: "main", created: false, tracking: "origin/main", ahead: 0, behind: 0 },
  gitDeleteBranch: undefined,
  gitAddWorktree: { path: "/tmp/wt" },
  gitRemoveWorktree: undefined,
  gitPruneWorktrees: undefined,
  gitMergeToSource: { merged: true, fastForward: true, newSourceCommit: "def" },
  gitPullFromSource: { merged: true, fastForward: true },
  gitAbortMerge: {},
  gitFinishMerge: { success: true },
  ghCreatePr: pr,
  ghMergePr: undefined,
  ghClosePr: undefined,
  ghReopenPr: undefined,
  ghMarkPrReady: undefined,
  ghSubmitPrReview: undefined,
  ghUpdatePrBranch: undefined,
  ghPostPrComment: {
    id: "1",
    author: { login: "dev" },
    body: "lgtm",
    createdAt: "2026-08-12T00:00:00.000Z",
  },
  ghDispatchWorkflow: undefined,
  ghRerunWorkflowRun: undefined,
  ghCancelWorkflowRun: undefined,
  ghDeleteWorkflowRun: undefined,
} as const satisfies Record<RemoteProcedureName, unknown>;

export function omittedProcedureNames(): RemoteProcedureName[] {
  return REMOTE_PROCEDURE_CONTRACTS.filter((procedure) => procedure.resultSchema === OMITTED).map(
    (procedure) => procedure.name as RemoteProcedureName,
  );
}
