import { describe, expect, it } from "vitest";
import {
  computeWslHostAccess,
  parseDefaultRouteGateway,
  parseNetworkingMode,
  parseResolvConfNameserver,
} from "./hostAccess";

describe("computeWslHostAccess", () => {
  it("uses the bounded async reader only after the live probe fails", async () => {
    const calls: Array<{ distro: string; path: string }> = [];
    await expect(
      computeWslHostAccess("Pōrā código", {
        probe: async () => undefined,
        readTextFile: async (distro, path) => {
          calls.push({ distro, path });
          return "nameserver 172.20.144.1\n";
        },
      }),
    ).resolves.toEqual({ kind: "gateway", ip: "172.20.144.1" });
    expect(calls).toEqual([
      {
        distro: "Pōrā código",
        path: "\\\\wsl.localhost\\Pōrā código\\etc\\resolv.conf",
      },
    ]);
  });

  it("does not touch the fallback reader when the live probe succeeds", async () => {
    await expect(
      computeWslHostAccess("Ubuntu", {
        probe: async () => ({ kind: "loopback" }),
        readTextFile: async () => {
          throw new Error("fallback must not run");
        },
      }),
    ).resolves.toEqual({ kind: "loopback" });
  });

  it("treats a timed-out or missing fallback as unresolved", async () => {
    await expect(
      computeWslHostAccess("Stopped", {
        probe: async () => undefined,
        readTextFile: async () => {
          throw new Error("timed out after 60000ms");
        },
      }),
    ).resolves.toBeUndefined();
  });
});

describe("parseNetworkingMode", () => {
  it("reads `mirrored` from the first line", () => {
    expect(parseNetworkingMode("mirrored\ndefault via 172.20.0.1 dev eth0\n")).toBe("mirrored");
  });

  it("reads `nat` and lowercases it", () => {
    expect(parseNetworkingMode("NAT\ndefault via 172.20.0.1 dev eth0")).toBe("nat");
  });

  it("reads `unknown` when wslinfo is absent", () => {
    expect(parseNetworkingMode("unknown\n")).toBe("unknown");
  });

  it("tolerates CRLF endings and leading blank lines", () => {
    expect(parseNetworkingMode("\r\n  mirrored  \r\ndefault via 10.0.0.1\r\n")).toBe("mirrored");
  });

  it("returns empty string for empty output", () => {
    expect(parseNetworkingMode("")).toBe("");
    expect(parseNetworkingMode("\n\n")).toBe("");
  });
});

describe("parseDefaultRouteGateway", () => {
  it("extracts the gateway from a normal default route", () => {
    expect(parseDefaultRouteGateway("default via 172.20.144.1 dev eth0 proto kernel")).toBe(
      "172.20.144.1",
    );
  });

  it("skips the mode line and finds the route on a later line", () => {
    expect(parseDefaultRouteGateway("nat\ndefault via 192.168.1.1 dev eth0")).toBe("192.168.1.1");
  });

  it("returns the first of multiple default routes", () => {
    const out = "default via 10.0.0.1 dev eth0\ndefault via 10.0.0.2 dev eth1\n";
    expect(parseDefaultRouteGateway(out)).toBe("10.0.0.1");
  });

  it("tolerates CRLF endings", () => {
    expect(parseDefaultRouteGateway("default via 172.20.0.1 dev eth0\r\n")).toBe("172.20.0.1");
  });

  it("returns undefined when there is no default route", () => {
    expect(
      parseDefaultRouteGateway("172.20.0.0/20 dev eth0 proto kernel scope link"),
    ).toBeUndefined();
  });

  it("returns undefined for garbage output", () => {
    expect(parseDefaultRouteGateway("cannot execute\nsome error text")).toBeUndefined();
  });

  it("ignores an out-of-range octet", () => {
    expect(parseDefaultRouteGateway("default via 999.1.1.1 dev eth0")).toBeUndefined();
  });
});

describe("parseResolvConfNameserver", () => {
  it("extracts a normal nameserver", () => {
    expect(parseResolvConfNameserver("nameserver 172.20.144.1\n")).toBe("172.20.144.1");
  });

  it("skips the DNS-tunneling virtual IP", () => {
    expect(parseResolvConfNameserver("nameserver 10.255.255.254\n")).toBeUndefined();
  });

  it("skips loopback nameservers", () => {
    expect(parseResolvConfNameserver("nameserver 127.0.0.1\nnameserver ::1\n")).toBeUndefined();
  });

  it("returns the first usable nameserver after skipping the virtual IP", () => {
    const out = "nameserver 10.255.255.254\nnameserver 172.20.0.1\n";
    expect(parseResolvConfNameserver(out)).toBe("172.20.0.1");
  });

  it("ignores comments and leading whitespace", () => {
    const out = "# generated by WSL\n  nameserver 8.8.8.8\n";
    expect(parseResolvConfNameserver(out)).toBe("8.8.8.8");
  });

  it("tolerates CRLF endings", () => {
    expect(parseResolvConfNameserver("nameserver 1.1.1.1\r\n")).toBe("1.1.1.1");
  });

  it("returns undefined for empty contents", () => {
    expect(parseResolvConfNameserver("")).toBeUndefined();
  });
});
