import { contextBridge, ipcRenderer } from "electron";
import type { LightcodeBridge, SupervisorEvent, UpdateStatus } from "../shared/ipc";

const CHANNELS = {
  pickFolder: "lightcode:pick-folder",
  pickFiles: "lightcode:pick-files",
  saveClipboardImage: "lightcode:save-clipboard-image",
  listWslDistros: "lightcode:list-wsl-distros",
  getAgentStatuses: "lightcode:get-agent-statuses",
  getThreadSnapshots: "lightcode:get-thread-snapshots",
  startThread: "lightcode:start-thread",
  sendThreadInput: "lightcode:send-thread-input",
  writeTerminal: "lightcode:write-terminal",
  resizeTerminal: "lightcode:resize-terminal",
  resolveThreadServerRequest: "lightcode:resolve-thread-server-request",
  closeThread: "lightcode:close-thread",
  startShell: "lightcode:start-shell",
  getGitStatus: "lightcode:get-git-status",
  getGitDiff: "lightcode:get-git-diff",
  getGitDiffBatch: "lightcode:get-git-diff-batch",
  getGitFileContent: "lightcode:get-git-file-content",
  gitStage: "lightcode:git-stage",
  gitUnstage: "lightcode:git-unstage",
  gitRevert: "lightcode:git-revert",
  gitStageAll: "lightcode:git-stage-all",
  gitUnstageAll: "lightcode:git-unstage-all",
  gitRevertAll: "lightcode:git-revert-all",
  gitCommit: "lightcode:git-commit",
  generateCommitMessage: "lightcode:generate-commit-message",
  generateTitle: "lightcode:generate-title",
  gitListBranches: "lightcode:git-list-branches",
  gitFetch: "lightcode:git-fetch",
  gitListWorktrees: "lightcode:git-list-worktrees",
  gitAddWorktree: "lightcode:git-add-worktree",
  gitRemoveWorktree: "lightcode:git-remove-worktree",
  gitPruneWorktrees: "lightcode:git-prune-worktrees",
  gitDeleteBranch: "lightcode:git-delete-branch",
  gitPull: "lightcode:git-pull",
  gitPush: "lightcode:git-push",
  gitSync: "lightcode:git-sync",
  gitGetWorktreeSourceBranch: "lightcode:git-get-worktree-source-branch",
  gitMergeToSource: "lightcode:git-merge-to-source",
  gitPullFromSource: "lightcode:git-pull-from-source",
  gitAbortMerge: "lightcode:git-abort-merge",
  gitRunMergetool: "lightcode:git-run-mergetool",
  gitFinishMerge: "lightcode:git-finish-merge",
  gitWatchProject: "lightcode:git-watch-project",
  gitWatchWorktrees: "lightcode:git-watch-worktrees",
  gitUnwatchProject: "lightcode:git-unwatch-project",
  searchProjectFiles: "lightcode:search-project-files",
  detectSetupScript: "lightcode:detect-setup-script",
  ghCheckAvailable: "lightcode:gh-check-available",
  ghCreatePr: "lightcode:gh-create-pr",
  ghGetPrForBranch: "lightcode:gh-get-pr-for-branch",
  ghMergePr: "lightcode:gh-merge-pr",
  ghClosePr: "lightcode:gh-close-pr",
  ghReopenPr: "lightcode:gh-reopen-pr",
  ghGetPrChecks: "lightcode:gh-get-pr-checks",
  openExternal: "lightcode:open-external",
  getSharedSettings: "lightcode:get-shared-settings",
  setSharedSettings: "lightcode:set-shared-settings",
  setWindowChrome: "lightcode:set-window-chrome",
  dbGetProjects: "lightcode:db-get-projects",
  dbGetThreads: "lightcode:db-get-threads",
  dbGetState: "lightcode:db-get-state",
  dbSetState: "lightcode:db-set-state",
  dbUpsertProject: "lightcode:db-upsert-project",
  dbUpsertThread: "lightcode:db-upsert-thread",
  dbDeleteThread: "lightcode:db-delete-thread",
  dbDeleteProject: "lightcode:db-delete-project",
  dbSyncAll: "lightcode:db-sync-all",
  supervisorEvent: "lightcode:supervisor-event",
  updateStatus: "lightcode:update-status",
  checkForUpdate: "lightcode:check-for-update",
  startUpdateDownload: "lightcode:start-update-download",
  installUpdate: "lightcode:install-update",
} as const;

const bridge: LightcodeBridge = {
  platform: process.platform,
  pickFolder: (defaultPath?) => ipcRenderer.invoke(CHANNELS.pickFolder, defaultPath),
  pickFiles: (options?) => ipcRenderer.invoke(CHANNELS.pickFiles, options),
  saveClipboardImage: (payload) => ipcRenderer.invoke(CHANNELS.saveClipboardImage, payload),
  listWslDistros: () => ipcRenderer.invoke(CHANNELS.listWslDistros),
  getAgentStatuses: (wslDistros) =>
    ipcRenderer.invoke(CHANNELS.getAgentStatuses, { wslDistros: wslDistros ?? [] }),
  getThreadSnapshots: () => ipcRenderer.invoke(CHANNELS.getThreadSnapshots),
  startThread: (payload) => ipcRenderer.invoke(CHANNELS.startThread, payload),
  sendThreadInput: (payload) => ipcRenderer.invoke(CHANNELS.sendThreadInput, payload),
  writeTerminal: (payload) => ipcRenderer.invoke(CHANNELS.writeTerminal, payload),
  resizeTerminal: (payload) => ipcRenderer.invoke(CHANNELS.resizeTerminal, payload),
  resolveThreadServerRequest: (payload) =>
    ipcRenderer.invoke(CHANNELS.resolveThreadServerRequest, payload),
  closeThread: (payload) => ipcRenderer.invoke(CHANNELS.closeThread, payload),
  startShell: (payload) => ipcRenderer.invoke(CHANNELS.startShell, payload),
  getGitStatus: (payload) => ipcRenderer.invoke(CHANNELS.getGitStatus, payload),
  getGitDiff: (payload) => ipcRenderer.invoke(CHANNELS.getGitDiff, payload),
  getGitDiffBatch: (payload) => ipcRenderer.invoke(CHANNELS.getGitDiffBatch, payload),
  getGitFileContent: (payload) => ipcRenderer.invoke(CHANNELS.getGitFileContent, payload),
  gitStage: (payload) => ipcRenderer.invoke(CHANNELS.gitStage, payload),
  gitUnstage: (payload) => ipcRenderer.invoke(CHANNELS.gitUnstage, payload),
  gitRevert: (payload) => ipcRenderer.invoke(CHANNELS.gitRevert, payload),
  gitStageAll: (payload) => ipcRenderer.invoke(CHANNELS.gitStageAll, payload),
  gitUnstageAll: (payload) => ipcRenderer.invoke(CHANNELS.gitUnstageAll, payload),
  gitRevertAll: (payload) => ipcRenderer.invoke(CHANNELS.gitRevertAll, payload),
  gitCommit: (payload) => ipcRenderer.invoke(CHANNELS.gitCommit, payload),
  generateCommitMessage: (payload) => ipcRenderer.invoke(CHANNELS.generateCommitMessage, payload),
  generateTitle: (payload) => ipcRenderer.invoke(CHANNELS.generateTitle, payload),
  gitListBranches: (payload) => ipcRenderer.invoke(CHANNELS.gitListBranches, payload),
  gitFetch: (payload) => ipcRenderer.invoke(CHANNELS.gitFetch, payload),
  gitListWorktrees: (payload) => ipcRenderer.invoke(CHANNELS.gitListWorktrees, payload),
  gitAddWorktree: (payload) => ipcRenderer.invoke(CHANNELS.gitAddWorktree, payload),
  gitRemoveWorktree: (payload) => ipcRenderer.invoke(CHANNELS.gitRemoveWorktree, payload),
  gitPruneWorktrees: (payload) => ipcRenderer.invoke(CHANNELS.gitPruneWorktrees, payload),
  gitDeleteBranch: (payload) => ipcRenderer.invoke(CHANNELS.gitDeleteBranch, payload),
  gitPull: (payload) => ipcRenderer.invoke(CHANNELS.gitPull, payload),
  gitPush: (payload) => ipcRenderer.invoke(CHANNELS.gitPush, payload),
  gitSync: (payload) => ipcRenderer.invoke(CHANNELS.gitSync, payload),
  gitGetWorktreeSourceBranch: (payload) =>
    ipcRenderer.invoke(CHANNELS.gitGetWorktreeSourceBranch, payload),
  gitMergeToSource: (payload) => ipcRenderer.invoke(CHANNELS.gitMergeToSource, payload),
  gitPullFromSource: (payload) => ipcRenderer.invoke(CHANNELS.gitPullFromSource, payload),
  gitAbortMerge: (payload) => ipcRenderer.invoke(CHANNELS.gitAbortMerge, payload),
  gitRunMergetool: (payload) => ipcRenderer.invoke(CHANNELS.gitRunMergetool, payload),
  gitFinishMerge: (payload) => ipcRenderer.invoke(CHANNELS.gitFinishMerge, payload),
  gitWatchProject: (payload) => ipcRenderer.invoke(CHANNELS.gitWatchProject, payload),
  gitWatchWorktrees: (payload) => ipcRenderer.invoke(CHANNELS.gitWatchWorktrees, payload),
  gitUnwatchProject: (payload) => ipcRenderer.invoke(CHANNELS.gitUnwatchProject, payload),
  searchProjectFiles: (payload) => ipcRenderer.invoke(CHANNELS.searchProjectFiles, payload),
  detectSetupScript: (payload) => ipcRenderer.invoke(CHANNELS.detectSetupScript, payload),
  ghCheckAvailable: (payload) => ipcRenderer.invoke(CHANNELS.ghCheckAvailable, payload),
  ghCreatePr: (payload) => ipcRenderer.invoke(CHANNELS.ghCreatePr, payload),
  ghGetPrForBranch: (payload) => ipcRenderer.invoke(CHANNELS.ghGetPrForBranch, payload),
  ghMergePr: (payload) => ipcRenderer.invoke(CHANNELS.ghMergePr, payload),
  ghClosePr: (payload) => ipcRenderer.invoke(CHANNELS.ghClosePr, payload),
  ghReopenPr: (payload) => ipcRenderer.invoke(CHANNELS.ghReopenPr, payload),
  ghGetPrChecks: (payload) => ipcRenderer.invoke(CHANNELS.ghGetPrChecks, payload),
  openExternal: (url) => ipcRenderer.invoke(CHANNELS.openExternal, url),
  getSharedSettings: () => ipcRenderer.invoke(CHANNELS.getSharedSettings),
  setSharedSettings: (settings) => ipcRenderer.invoke(CHANNELS.setSharedSettings, settings),
  setWindowChrome: (payload) => ipcRenderer.invoke(CHANNELS.setWindowChrome, payload),
  dbGetProjects: () => ipcRenderer.invoke(CHANNELS.dbGetProjects),
  dbGetThreads: () => ipcRenderer.invoke(CHANNELS.dbGetThreads),
  dbGetState: (key) => ipcRenderer.invoke(CHANNELS.dbGetState, key),
  dbSetState: (key, value) => ipcRenderer.invoke(CHANNELS.dbSetState, key, value),
  dbUpsertProject: (project) => ipcRenderer.invoke(CHANNELS.dbUpsertProject, project),
  dbUpsertThread: (thread) => ipcRenderer.invoke(CHANNELS.dbUpsertThread, thread),
  dbDeleteThread: (threadId) => ipcRenderer.invoke(CHANNELS.dbDeleteThread, threadId),
  dbDeleteProject: (projectId) => ipcRenderer.invoke(CHANNELS.dbDeleteProject, projectId),
  dbSyncAll: (projects, threads, viewJson) =>
    ipcRenderer.invoke(CHANNELS.dbSyncAll, projects, threads, viewJson),
  onSupervisorEvent(listener) {
    const handler = (_event: Electron.IpcRendererEvent, payload: SupervisorEvent) => {
      listener(payload);
    };
    ipcRenderer.on(CHANNELS.supervisorEvent, handler);
    return () => {
      ipcRenderer.removeListener(CHANNELS.supervisorEvent, handler);
    };
  },
  checkForUpdate: () => ipcRenderer.invoke(CHANNELS.checkForUpdate),
  startUpdateDownload: () => ipcRenderer.invoke(CHANNELS.startUpdateDownload),
  installUpdate: () => ipcRenderer.invoke(CHANNELS.installUpdate),
  onUpdateStatus(listener) {
    const handler = (_event: Electron.IpcRendererEvent, status: UpdateStatus) => {
      listener(status);
    };
    ipcRenderer.on(CHANNELS.updateStatus, handler);
    return () => {
      ipcRenderer.removeListener(CHANNELS.updateStatus, handler);
    };
  },
};

contextBridge.exposeInMainWorld("lightcode", bridge);
