/**
 * Register the PWA service worker so the app is installable and the shell is
 * available offline. Best-effort and non-blocking:
 *  - skipped in dev (the worker would cache HMR assets) and in non-secure
 *    contexts (service workers require https / localhost — the LAN-served
 *    build over plain http simply runs without one).
 *  - the worker itself is served as a static file when hosted, or generated by
 *    the desktop at /service-worker.js when paired over the LAN.
 */
export function registerServiceWorker(): void {
  if (import.meta.env.DEV) return;
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;
  if (typeof window !== "undefined" && window.isSecureContext === false) return;

  const register = () => {
    const scope = import.meta.env.BASE_URL;
    navigator.serviceWorker.register(`${scope}service-worker.js`, { scope }).catch(() => {
      // Registration failing (e.g. worker not served, blocked) must never break
      // the app — it just means no offline shell / install prompt this session.
    });
  };

  if (document.readyState === "complete") {
    register();
  } else {
    window.addEventListener("load", register, { once: true });
  }
}
