export type SettingsSection =
  | "general"
  | "audio"
  | "appearance"
  | "terminal"
  | "threads"
  | "git"
  | "notifications"
  | "ai"
  | "acpRegistry"
  | "agentsGeneral"
  | "search"
  | "agents"
  | "browser"
  | "archived"
  | "about"
  | "dev"
  | `agents:${string}`;
