/**
 * Auto-generated by `scripts/generate-main-promotion-messages.mjs`.
 *
 * The promotion progress window is created in Electron main before the renderer
 * and its i18n runtime exist, so it cannot consult the `.po` catalogs at
 * runtime. This committed subset carries only the two strings that window
 * renders, copied verbatim from `src/shared/messages.ts` (source text) and
 * the renderer locale catalogs (translations). Do not edit this file by hand;
 * regenerate it and let `promotionMessages.generated.test.ts` prove it is
 * current.
 */
import type { SupportedLocale } from "@/shared/locale";

export type PromotionProgressMessageKey =
  | "desktop.promotion.progress.title"
  | "desktop.promotion.progress.body";

export const PROMOTION_PROGRESS_MESSAGES: Record<
  PromotionProgressMessageKey,
  Record<SupportedLocale, string>
> = {
  "desktop.promotion.progress.title": {
    en: "Poracode",
    es: "Poracode",
    ru: "Poracode",
    uk: "Poracode",
    "zh-CN": "Poracode",
    ja: "Poracode",
    "pt-BR": "Poracode",
    de: "Poracode",
    fr: "Poracode",
    ko: "Poracode",
    pl: "Poracode",
    vi: "Poracode",
    tr: "Poracode",
  },
  "desktop.promotion.progress.body": {
    en: "Promoting this profile into the owned data root…",
    es: "Promoviendo este perfil al directorio de datos propio…",
    ru: "Перенос этого профиля в собственный корневой каталог данных…",
    uk: "Перенесення цього профілю у власний кореневий каталог даних…",
    "zh-CN": "正在将此个人资料迁移到专属数据根目录…",
    ja: "このプロフィールを専用データルートへ移行しています…",
    "pt-BR": "Movendo este perfil para o diretório de dados próprio…",
    de: "Dieses Profil wird in das eigene Datenverzeichnis übernommen…",
    fr: "Transfert de ce profil vers la racine de données dédiée…",
    ko: "이 프로필을 전용 데이터 루트로 이전하는 중…",
    pl: "Przenoszenie tego profilu do własnego katalogu głównego danych…",
    vi: "Đang chuyển hồ sơ này vào thư mục gốc dữ liệu riêng…",
    tr: "Bu profil, kendi veri köküne taşınıyor…",
  },
};
