import { defineRoute } from "../helpers";
import {
  emptyJsonObjectSchema,
  profileCoreStatsSchema,
  profileDevicesResponseSchema,
  profileIdentityResponseSchema,
  profileIdentitySchema,
  profileStatsRequestSchema,
  profileTokenStatsSchema,
  projectNotesReadResultSchema,
  projectNotesWriteBodySchema,
  providerUsageResponseSchema,
  remoteAccessTokenResultSchema,
  remoteAgentStatusesSchema,
  remoteEnvironmentDescriptorSchema,
  remoteHostUpdateStateSchema,
  remoteSettingsPatchWireSchema,
  remoteShellSnapshotWireSchema,
  settingsReadResultWireSchema,
  settingsWriteResultWireSchema,
  remoteTokenExchangePayloadSchema,
  remoteWebSocketTicketResultSchema,
  forwardEnterQuerySchema,
} from "../routeSchemas";
import type { RemoteHttpRouteContract } from "../types";

export const sessionRoutes: readonly RemoteHttpRouteContract[] = [
  defineRoute({
    id: "environment",
    method: "GET",
    path: "/.well-known/poracode/environment",
    auth: "public",
    scopes: [],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteEnvironmentDescriptorSchema,
    },
  }),
  defineRoute({
    id: "environment-legacy",
    method: "GET",
    path: "/.well-known/lightcode/environment",
    auth: "public",
    scopes: [],
    legacy: true,
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteEnvironmentDescriptorSchema,
    },
  }),
  defineRoute({
    id: "forward-enter",
    method: "GET",
    path: "/forward/{forwardId}/enter",
    auth: "forward-enter-token",
    scopes: [],
    queryParameters: ["fwt"],
    request: { bodyKind: "empty", querySchema: forwardEnterQuerySchema },
    response: {
      wireKind: "redirect-html",
      status: 302,
      errorStatus: 400,
      errorBodyKind: "html",
    },
  }),
  defineRoute({
    id: "token-exchange",
    method: "POST",
    path: "/oauth/token",
    auth: "pairing-token",
    scopes: [],
    request: { bodyKind: "json", jsonSchema: remoteTokenExchangePayloadSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteAccessTokenResultSchema,
    },
  }),
  defineRoute({
    id: "websocket-ticket",
    method: "POST",
    path: "/api/auth/websocket-ticket",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteWebSocketTicketResultSchema,
    },
  }),
  defineRoute({
    id: "shell-snapshot",
    method: "GET",
    path: "/api/snapshot",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteShellSnapshotWireSchema,
    },
  }),
  defineRoute({
    id: "agent-statuses",
    method: "GET",
    path: "/api/agent-statuses",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteAgentStatusesSchema,
    },
  }),
  defineRoute({
    id: "host-update",
    method: "GET",
    path: "/api/host-update",
    auth: "bearer",
    scopes: ["projects:manage"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteHostUpdateStateSchema,
    },
  }),
  defineRoute({
    id: "host-update-check",
    method: "POST",
    path: "/api/host-update/check",
    auth: "bearer",
    scopes: ["projects:manage"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteHostUpdateStateSchema,
    },
  }),
  defineRoute({
    id: "host-update-install",
    method: "POST",
    path: "/api/host-update/install",
    auth: "bearer",
    scopes: ["projects:manage"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 202,
      jsonSchema: emptyJsonObjectSchema,
    },
  }),
  defineRoute({
    id: "provider-usage",
    method: "GET",
    path: "/api/provider-usage",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: providerUsageResponseSchema,
    },
  }),
  defineRoute({
    id: "project-notes-read",
    method: "GET",
    path: "/api/projects/{projectId}/notes",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: projectNotesReadResultSchema,
    },
  }),
  defineRoute({
    id: "project-notes-write",
    method: "POST",
    path: "/api/projects/{projectId}/notes",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: projectNotesWriteBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: emptyJsonObjectSchema,
    },
  }),
  defineRoute({
    id: "profile-devices",
    method: "GET",
    path: "/api/profile/devices",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileDevicesResponseSchema,
    },
  }),
  defineRoute({
    id: "profile-core-stats",
    method: "POST",
    path: "/api/profile/core-stats",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "json", jsonSchema: profileStatsRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileCoreStatsSchema,
    },
  }),
  defineRoute({
    id: "profile-token-stats",
    method: "POST",
    path: "/api/profile/token-stats",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "json", jsonSchema: profileStatsRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileTokenStatsSchema,
    },
  }),
  defineRoute({
    id: "profile-identity",
    method: "POST",
    path: "/api/profile/identity",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: profileIdentitySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileIdentityResponseSchema,
    },
  }),
  defineRoute({
    id: "settings-read",
    method: "GET",
    path: "/api/settings",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: settingsReadResultWireSchema,
    },
  }),
  defineRoute({
    id: "settings-write",
    method: "POST",
    path: "/api/settings",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: remoteSettingsPatchWireSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: settingsWriteResultWireSchema,
    },
  }),
];
