import { z } from "zod";

import { defineRoute } from "../helpers";
import { auditEvent, noAudit } from "../../auditKinds";
import { remoteHostDescribeSchema } from "../../../hostControlProtocol";
import {
  catalogMembershipRequestSchema,
  catalogMembershipResponseSchema,
  catalogProjectListPageSchema,
  emptyJsonObjectSchema,
  profileCoreStatsSchema,
  profileDevicesResponseSchema,
  profileIdentityResponseSchema,
  profileIdentitySchema,
  profileStatsRequestSchema,
  profileTokenStatsSchema,
  projectListQuerySchema,
  projectNotesReadResultSchema,
  projectNotesWriteBodySchema,
  providerUsageResponseSchema,
  remoteAccessTokenResultSchema,
  remoteAgentSlashCommandsSchema,
  remoteAgentStatusesSchema,
  remoteEnvironmentDescriptorSchema,
  remoteHostUpdateStateSchema,
  remoteMcpSettingsCommandSchema,
  remoteMcpSettingsOperationResultSchema,
  remoteMcpSettingsOperationSchema,
  remoteMcpSettingsReadResultSchema,
  remoteSettingsPatchWireSchema,
  remoteShellSnapshotWireSchema,
  settingsReadResultWireSchema,
  settingsWriteResultWireSchema,
  remoteTokenExchangePayloadSchema,
  remoteWebSocketTicketResultSchema,
  forwardEnterQuerySchema,
  shellSnapshotQuerySchema,
} from "../routeSchemas";
import type { RemoteHttpRouteContract } from "../types";

export const sessionRoutes: readonly RemoteHttpRouteContract[] = [
  defineRoute({
    id: "environment",
    method: "GET",
    path: "/.well-known/poracode/environment",
    auth: "public",
    scopes: [],
    audit: noAudit("public descriptor"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteEnvironmentDescriptorSchema,
    },
  }),
  defineRoute({
    id: "environment-legacy",
    method: "GET",
    path: "/.well-known/lightcode/environment",
    auth: "public",
    scopes: [],
    audit: noAudit("public descriptor"),
    legacy: true,
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteEnvironmentDescriptorSchema,
    },
  }),
  defineRoute({
    id: "forward-enter",
    method: "GET",
    path: "/forward/{forwardId}/enter",
    auth: "forward-enter-token",
    scopes: [],
    audit: noAudit("browser redirect with enter token"),
    queryParameters: ["fwt"],
    request: { bodyKind: "empty", querySchema: forwardEnterQuerySchema },
    response: {
      wireKind: "redirect-html",
      status: 302,
      errorStatus: 400,
      errorBodyKind: "html",
    },
  }),
  defineRoute({
    id: "token-exchange",
    method: "POST",
    path: "/oauth/token",
    auth: "pairing-token",
    scopes: [],
    audit: noAudit("orchestrator records token_exchange"),
    request: { bodyKind: "json", jsonSchema: remoteTokenExchangePayloadSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteAccessTokenResultSchema,
    },
  }),
  defineRoute({
    id: "websocket-ticket",
    method: "POST",
    path: "/api/auth/websocket-ticket",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("session ticket mint"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteWebSocketTicketResultSchema,
    },
  }),
  defineRoute({
    id: "shell-snapshot",
    method: "GET",
    path: "/api/snapshot",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    // Gate 4 hazard #3 payload split: `threadLimit` bounds the thread list to
    // its first rows plus `threadsNextCursor`; clients that omit it keep the
    // historical full list and never see the cursor field.
    //
    // B4 adds the declared-client bundle (`reads`, `order`, `projectLimit`,
    // `summaries`, byte caps); all of it is ignored without the `reads` echo.
    queryParameters: [
      "reads",
      "threadLimit",
      "order",
      "projectLimit",
      "summaries",
      "maxBytes",
      "maxDecodeBytes",
    ],
    request: { bodyKind: "empty", querySchema: shellSnapshotQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteShellSnapshotWireSchema,
    },
  }),
  defineRoute({
    id: "agent-statuses",
    method: "GET",
    path: "/api/agent-statuses",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    // WS3-A payload split: `slashCommands=0` omits the per-agent slash-command
    // catalogs (the dominant payload bulk) so clients can fetch one agent's
    // catalog lazily from agent-slash-commands instead.
    queryParameters: ["slashCommands"],
    request: {
      bodyKind: "empty",
      querySchema: z.object({ slashCommands: z.boolean().optional() }),
    },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteAgentStatusesSchema,
    },
  }),
  defineRoute({
    id: "agent-slash-commands",
    method: "GET",
    path: "/api/agents/{kind}/slash-commands",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteAgentSlashCommandsSchema,
    },
  }),
  defineRoute({
    id: "host-update",
    method: "GET",
    path: "/api/host-update",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteHostUpdateStateSchema,
    },
  }),
  defineRoute({
    id: "host-update-check",
    method: "POST",
    path: "/api/host-update/check",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteHostUpdateStateSchema,
    },
  }),
  defineRoute({
    id: "host-update-install",
    method: "POST",
    path: "/api/host-update/install",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 202,
      jsonSchema: emptyJsonObjectSchema,
    },
  }),
  defineRoute({
    id: "host-describe",
    method: "GET",
    path: "/api/host/describe",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteHostDescribeSchema,
    },
  }),
  defineRoute({
    id: "provider-usage",
    method: "GET",
    path: "/api/provider-usage",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: providerUsageResponseSchema,
    },
  }),
  defineRoute({
    id: "project-notes-read",
    method: "GET",
    path: "/api/projects/{projectId}/notes",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: projectNotesReadResultSchema,
    },
  }),
  defineRoute({
    id: "project-notes-write",
    method: "POST",
    path: "/api/projects/{projectId}/notes",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: projectNotesWriteBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: emptyJsonObjectSchema,
    },
  }),
  defineRoute({
    id: "project-list",
    method: "GET",
    path: "/api/projects",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    // B4 `reads=bounded-v1` only: declared clients page projects in paint
    // (`pj1.` sort-order cursor) or walk exact membership (`pi1.` id frontier).
    // An undeclared request is a protocol error, never a silent legacy read.
    queryParameters: [
      "reads",
      "cursor",
      "mode",
      "order",
      "projectLimit",
      "maxBytes",
      "maxDecodeBytes",
    ],
    request: { bodyKind: "empty", querySchema: projectListQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: catalogProjectListPageSchema,
    },
  }),
  defineRoute({
    id: "catalog-membership",
    method: "POST",
    path: "/api/catalog/membership",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    // B4 authoritative existence set behind the client's deletion gate: one
    // bounded (≤200 ids per list) read-only membership confirmation, no writes.
    request: { bodyKind: "json", jsonSchema: catalogMembershipRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: catalogMembershipResponseSchema,
    },
  }),
  defineRoute({
    id: "profile-devices",
    method: "GET",
    path: "/api/profile/devices",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileDevicesResponseSchema,
    },
  }),
  defineRoute({
    id: "profile-core-stats",
    method: "POST",
    path: "/api/profile/core-stats",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "json", jsonSchema: profileStatsRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileCoreStatsSchema,
    },
  }),
  defineRoute({
    id: "profile-token-stats",
    method: "POST",
    path: "/api/profile/token-stats",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "json", jsonSchema: profileStatsRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileTokenStatsSchema,
    },
  }),
  defineRoute({
    id: "profile-identity",
    method: "POST",
    path: "/api/profile/identity",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: profileIdentitySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: profileIdentityResponseSchema,
    },
  }),
  defineRoute({
    id: "settings-read",
    method: "GET",
    path: "/api/settings",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: settingsReadResultWireSchema,
    },
  }),
  defineRoute({
    id: "settings-write",
    method: "POST",
    path: "/api/settings",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remoteSettingsPatchWireSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: settingsWriteResultWireSchema,
    },
  }),
  defineRoute({
    id: "mcp-settings-read",
    method: "GET",
    path: "/api/settings/mcp-servers",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteMcpSettingsReadResultSchema,
    },
  }),
  defineRoute({
    id: "mcp-settings-command",
    method: "POST",
    path: "/api/settings/mcp-servers/command",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remoteMcpSettingsCommandSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteMcpSettingsReadResultSchema,
    },
  }),
  defineRoute({
    id: "mcp-settings-operation",
    method: "POST",
    path: "/api/settings/mcp-servers/operation",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remoteMcpSettingsOperationSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteMcpSettingsOperationResultSchema,
    },
  }),
];
