import { defineRoute, remoteOkResponseSchema } from "../helpers";
import {
  pathScopedEmptyBodySchema,
  requestResolveBodySchema,
  startExistingThreadBodySchema,
  terminalResizeBodySchema,
  terminalWriteBodySchema,
  threadCommandBodySchema,
  threadGoalHttpBodySchema,
  threadRuntimeTruncateBodySchema,
  threadSendBodySchema,
  threadSteerSetBodySchema,
} from "../routeBodies";
import {
  remoteRuntimeItemsPageSchema,
  remoteThreadSnapshotSchema,
  startShellPayloadSchema,
  startThreadResultSchema,
  threadHistoryItemsQuerySchema,
  threadHistoryQuerySchema,
} from "../routeSchemas";
import type { RemoteHttpRouteContract } from "../types";

export const threadRoutes: readonly RemoteHttpRouteContract[] = [
  defineRoute({
    id: "thread-history-items",
    method: "GET",
    path: "/api/threads/{threadId}/history/items",
    auth: "bearer",
    scopes: ["session:read"],
    queryParameters: ["beforePosition", "limit", "targetTimelineEntryCount"],
    request: { bodyKind: "empty", querySchema: threadHistoryItemsQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteRuntimeItemsPageSchema,
    },
  }),
  defineRoute({
    id: "thread-history",
    method: "GET",
    path: "/api/threads/{threadId}/history",
    auth: "bearer",
    scopes: ["session:read"],
    queryParameters: ["runtimePage", "targetTimelineEntryCount"],
    request: { bodyKind: "empty", querySchema: threadHistoryQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteThreadSnapshotSchema,
    },
  }),
  defineRoute({
    id: "thread-start-existing",
    method: "POST",
    path: "/api/threads/start",
    auth: "bearer",
    scopes: ["session:operate"],
    idempotency: "command-id-header",
    request: { bodyKind: "json", jsonSchema: startExistingThreadBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: startThreadResultSchema,
    },
  }),
  defineRoute({
    id: "terminal-start",
    method: "POST",
    path: "/api/terminal/start",
    auth: "bearer",
    scopes: ["terminal:operate"],
    request: { bodyKind: "json", jsonSchema: startShellPayloadSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-runtime-truncate",
    method: "POST",
    path: "/api/threads/{threadId}/runtime/truncate",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: threadRuntimeTruncateBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-command",
    method: "POST",
    path: "/api/threads/{threadId}/command",
    auth: "bearer",
    scopes: ["session:operate"],
    idempotency: "command-id-header-for-start-kind",
    request: { bodyKind: "json", jsonSchema: threadCommandBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-send",
    method: "POST",
    path: "/api/threads/{threadId}/send",
    auth: "bearer",
    scopes: ["session:operate"],
    idempotency: "command-id-header",
    request: { bodyKind: "json", jsonSchema: threadSendBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-interrupt",
    method: "POST",
    path: "/api/threads/{threadId}/interrupt",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-goal",
    method: "POST",
    path: "/api/threads/{threadId}/goal",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: threadGoalHttpBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-close",
    method: "POST",
    path: "/api/threads/{threadId}/close",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-steer-set",
    method: "POST",
    path: "/api/threads/{threadId}/steer/set",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: threadSteerSetBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-steer-clear",
    method: "POST",
    path: "/api/threads/{threadId}/steer/clear",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "terminal-write",
    method: "POST",
    path: "/api/threads/{threadId}/terminal/write",
    auth: "bearer",
    scopes: ["terminal:operate"],
    request: { bodyKind: "json", jsonSchema: terminalWriteBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "terminal-resize",
    method: "POST",
    path: "/api/threads/{threadId}/terminal/resize",
    auth: "bearer",
    scopes: ["terminal:operate"],
    request: { bodyKind: "json", jsonSchema: terminalResizeBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "terminal-close",
    method: "POST",
    path: "/api/threads/{threadId}/terminal/close",
    auth: "bearer",
    scopes: ["terminal:operate"],
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "request-resolve",
    method: "POST",
    path: "/api/threads/{threadId}/requests/resolve",
    auth: "bearer",
    scopes: ["requests:resolve"],
    request: { bodyKind: "json", jsonSchema: requestResolveBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
];
