import { defineRoute, remoteOkResponseSchema } from "../helpers";
import { auditEvent, noAudit } from "../../auditKinds";
import {
  checkpointRevertBodySchema,
  pathScopedEmptyBodySchema,
  requestResolveBodySchema,
  startExistingThreadBodySchema,
  terminalResizeBodySchema,
  terminalWriteBodySchema,
  threadCommandBodySchema,
  threadGoalHttpBodySchema,
  threadRuntimeTruncateBodySchema,
  threadSendBodySchema,
  threadSteerSetBodySchema,
} from "../routeBodies";
import {
  historyTurnPageSchema,
  remoteRuntimeGapAcknowledgeBodySchema,
  remoteRuntimeGapAcknowledgeResultSchema,
  remoteRuntimeGapReadResultSchema,
  remoteRuntimeItemsPageSchema,
  remoteThreadListPageSchema,
  remoteThreadSnapshotSchema,
  runtimeGapAcknowledgeQuerySchema,
  runtimeGapQuerySchema,
  startShellPayloadSchema,
  startThreadResultSchema,
  threadHistoryItemsQuerySchema,
  threadHistoryQuerySchema,
  threadListQuerySchema,
  threadTurnsQuerySchema,
} from "../routeSchemas";
import { checkpointRevertResultSchema } from "../../../contracts";
import type { RemoteHttpRouteContract } from "../types";

export const threadRoutes: readonly RemoteHttpRouteContract[] = [
  defineRoute({
    id: "thread-list",
    method: "GET",
    path: "/api/threads",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    // Gate 4 hazard #3: continuation pages for a threadLimit-bounded shell
    // snapshot. Clients only reach this route after the snapshot returned a
    // threadsNextCursor, so hosts without it are never called.
    //
    // B4 widens this route additively: `reads=bounded-v1` selects paint order
    // (`order`), exact-membership inventory mode (`mode=inventory`), the
    // summaries opt-in and per-response byte caps. Undeclared requests keep the
    // existing `tp1.` cursor and required `limit`.
    queryParameters: [
      "reads",
      "cursor",
      "limit",
      "order",
      "mode",
      "summaries",
      "maxBytes",
      "maxDecodeBytes",
    ],
    request: { bodyKind: "empty", querySchema: threadListQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteThreadListPageSchema,
    },
  }),
  defineRoute({
    id: "thread-history-items",
    method: "GET",
    path: "/api/threads/{threadId}/history/items",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    queryParameters: [
      "reads",
      "notices",
      "beforePosition",
      "limit",
      "targetTimelineEntryCount",
      "maxBytes",
      "maxDecodeBytes",
    ],
    request: { bodyKind: "empty", querySchema: threadHistoryItemsQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteRuntimeItemsPageSchema,
    },
  }),
  defineRoute({
    id: "thread-history",
    method: "GET",
    path: "/api/threads/{threadId}/history",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    queryParameters: [
      "reads",
      "notices",
      "runtimePage",
      "targetTimelineEntryCount",
      "omitScrollback",
      "completedTurnsLimit",
      "maxBytes",
      "maxDecodeBytes",
    ],
    request: { bodyKind: "empty", querySchema: threadHistoryQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteThreadSnapshotSchema,
    },
  }),
  defineRoute({
    id: "thread-turns",
    method: "GET",
    path: "/api/threads/{threadId}/turns",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    // B4 declared-only completed-turn continuation: `ct1.<idx>` pages older
    // turns than the bounded history tail, newest-first `completedTurnsLimit`
    // then exclusive-older pages. Undeclared requests are a protocol error.
    queryParameters: [
      "reads",
      "notices",
      "cursor",
      "limit",
      "completedTurnsLimit",
      "maxBytes",
      "maxDecodeBytes",
    ],
    request: { bodyKind: "empty", querySchema: threadTurnsQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: historyTurnPageSchema,
    },
  }),
  defineRoute({
    id: "thread-start-existing",
    method: "POST",
    path: "/api/threads/start",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("thread_create"),
    idempotency: "command-id-header-unless-ensure-running",
    request: { bodyKind: "json", jsonSchema: startExistingThreadBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: startThreadResultSchema,
    },
  }),
  defineRoute({
    id: "terminal-start",
    method: "POST",
    path: "/api/terminal/start",
    auth: "bearer",
    scopes: ["terminal:operate"],
    audit: auditEvent("thread_create"),
    request: { bodyKind: "json", jsonSchema: startShellPayloadSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-runtime-truncate",
    method: "POST",
    path: "/api/threads/{threadId}/runtime/truncate",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: threadRuntimeTruncateBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-checkpoint-revert",
    method: "POST",
    path: "/api/threads/{threadId}/checkpoint-revert",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    idempotency: "command-id-header",
    request: { bodyKind: "json", jsonSchema: checkpointRevertBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: checkpointRevertResultSchema,
    },
  }),
  defineRoute({
    id: "thread-command",
    method: "POST",
    path: "/api/threads/{threadId}/command",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    // `start` keeps its stable automatic receipt identity; the narrow
    // catalog-mutation kinds (`reorder`, `set-workspace`) REQUIRE the
    // command-id header (refused before any effect without it) and run under
    // the receipt. Other metadata kinds keep their historical non-receipted
    // dispatch.
    idempotency: "command-id-header-for-start-and-catalog-kinds",
    request: { bodyKind: "json", jsonSchema: threadCommandBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-send",
    method: "POST",
    path: "/api/threads/{threadId}/send",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("thread_send"),
    idempotency: "command-id-header",
    request: { bodyKind: "json", jsonSchema: threadSendBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-interrupt",
    method: "POST",
    path: "/api/threads/{threadId}/interrupt",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("thread_stop"),
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-goal",
    method: "POST",
    path: "/api/threads/{threadId}/goal",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: threadGoalHttpBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-close",
    method: "POST",
    path: "/api/threads/{threadId}/close",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("thread_stop"),
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-steer-set",
    method: "POST",
    path: "/api/threads/{threadId}/steer/set",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: threadSteerSetBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "thread-steer-clear",
    method: "POST",
    path: "/api/threads/{threadId}/steer/clear",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "terminal-write",
    method: "POST",
    path: "/api/threads/{threadId}/terminal/write",
    auth: "bearer",
    scopes: ["terminal:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: terminalWriteBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "terminal-resize",
    method: "POST",
    path: "/api/threads/{threadId}/terminal/resize",
    auth: "bearer",
    scopes: ["terminal:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: terminalResizeBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "terminal-close",
    method: "POST",
    path: "/api/threads/{threadId}/terminal/close",
    auth: "bearer",
    scopes: ["terminal:operate"],
    audit: auditEvent("thread_stop"),
    request: { bodyKind: "json", jsonSchema: pathScopedEmptyBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "request-resolve",
    method: "POST",
    path: "/api/threads/{threadId}/requests/resolve",
    auth: "bearer",
    scopes: ["requests:resolve"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: requestResolveBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  // B1 declared-only durable-gap recovery: the descriptor precondition read
  // and the explicit acknowledgement. `notices=v1` is required on BOTH routes
  // (a writer is always a client that declared it can render the notice), and
  // the acknowledgement carries the standard command-id receipt.
  defineRoute({
    id: "thread-runtime-gap",
    method: "GET",
    path: "/api/threads/{threadId}/runtime/gap",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    queryParameters: ["notices"],
    request: { bodyKind: "empty", querySchema: runtimeGapQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteRuntimeGapReadResultSchema,
    },
  }),
  defineRoute({
    id: "thread-runtime-gap-acknowledge",
    method: "POST",
    path: "/api/threads/{threadId}/runtime/gap/acknowledge",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    idempotency: "command-id-header",
    queryParameters: ["notices"],
    request: {
      bodyKind: "json",
      jsonSchema: remoteRuntimeGapAcknowledgeBodySchema,
      querySchema: runtimeGapAcknowledgeQuerySchema,
    },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteRuntimeGapAcknowledgeResultSchema,
    },
  }),
];
