import { defineRoute, remoteOkResponseSchema } from "../helpers";
import {
  attachmentUploadQuerySchema,
  attachmentUploadResultSchema,
  browserStateResultSchema,
  localImageQuerySchema,
  prWatchInputSchema,
  prWatchAgentSyncSchema,
  prWatchKeySchema,
  prWatchReadQuerySchema,
  prWatchReadResultSchema,
  prWatchUpsertResultSchema,
  remoteBrowserCommandSchema,
  remoteGitCallPayloadSchema,
  remotePortEnterRequestSchema,
  remotePortEnterResultSchema,
  remotePortForwardRequestSchema,
  remotePortForwardResultSchema,
  remotePortUnforwardRequestSchema,
  remotePortsStateSchema,
  remoteProjectCommandResultSchema,
  remoteProjectCommandSchema,
  remoteProjectSettingsSchema,
  remotePushRegistrationResultSchema,
  remotePushRegistrationSchema,
  remotePushUnregisterSchema,
  remoteScheduleCommandSchema,
  remoteScheduleRunsQuerySchema,
  remoteScheduleRunsResponseSchema,
  remoteSchedulesResponseSchema,
  remoteWebPushConfigResultSchema,
  runtimeImageQuerySchema,
} from "../routeSchemas";
import type { RemoteHttpRouteContract } from "../types";

export const workspaceRoutes: readonly RemoteHttpRouteContract[] = [
  defineRoute({
    id: "local-image",
    method: "GET",
    path: "/api/files/image",
    auth: "bearer-or-query",
    scopes: ["session:read"],
    queryParameters: ["path", "access_token"],
    request: { bodyKind: "empty", querySchema: localImageQuerySchema },
    response: {
      wireKind: "binary",
      status: 200,
      contentType: "image/*",
    },
  }),
  defineRoute({
    id: "runtime-image",
    method: "GET",
    path: "/api/threads/{threadId}/items/{itemId}/image",
    auth: "bearer-or-query",
    scopes: ["session:read"],
    queryParameters: ["path", "access_token"],
    request: { bodyKind: "empty", querySchema: runtimeImageQuerySchema },
    response: {
      wireKind: "binary",
      status: 200,
      contentType: "image/*",
    },
  }),
  defineRoute({
    id: "attachment-upload",
    method: "POST",
    path: "/api/files/attachment",
    auth: "bearer",
    scopes: ["session:operate"],
    queryParameters: ["threadId", "name"],
    request: { bodyKind: "raw-upload", querySchema: attachmentUploadQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: attachmentUploadResultSchema,
    },
  }),
  defineRoute({
    id: "schedules-read",
    method: "GET",
    path: "/api/schedules",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteSchedulesResponseSchema,
    },
  }),
  defineRoute({
    id: "schedules-command",
    method: "POST",
    path: "/api/schedules/command",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: remoteScheduleCommandSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteSchedulesResponseSchema,
    },
  }),
  defineRoute({
    id: "schedule-runs-read",
    method: "GET",
    path: "/api/schedules/runs",
    auth: "bearer",
    scopes: ["session:read"],
    queryParameters: ["id"],
    request: { bodyKind: "empty", querySchema: remoteScheduleRunsQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteScheduleRunsResponseSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-read",
    method: "GET",
    path: "/api/pr-watches",
    auth: "bearer",
    scopes: ["session:read"],
    queryParameters: ["projectId", "prNumber"],
    request: { bodyKind: "empty", querySchema: prWatchReadQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: prWatchReadResultSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-check",
    method: "POST",
    path: "/api/pr-watches/check",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: prWatchKeySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-agent-sync",
    method: "POST",
    path: "/api/pr-watches/agent",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: prWatchAgentSyncSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-upsert",
    method: "POST",
    path: "/api/pr-watches",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: prWatchInputSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: prWatchUpsertResultSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-delete",
    method: "DELETE",
    path: "/api/pr-watches",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: prWatchKeySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "browser-state",
    method: "GET",
    path: "/api/browser/state",
    auth: "bearer",
    scopes: ["session:read"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: browserStateResultSchema,
    },
  }),
  defineRoute({
    id: "browser-command",
    method: "POST",
    path: "/api/browser/command",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: remoteBrowserCommandSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: browserStateResultSchema,
    },
  }),
  defineRoute({
    id: "ports-read",
    method: "GET",
    path: "/api/ports",
    auth: "bearer",
    scopes: ["ports:forward"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePortsStateSchema,
    },
  }),
  defineRoute({
    id: "port-forward",
    method: "POST",
    path: "/api/ports/forward",
    auth: "bearer",
    scopes: ["ports:forward"],
    request: { bodyKind: "json", jsonSchema: remotePortForwardRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePortForwardResultSchema,
    },
  }),
  defineRoute({
    id: "port-enter",
    method: "POST",
    path: "/api/ports/enter",
    auth: "bearer",
    scopes: ["ports:forward"],
    request: { bodyKind: "json", jsonSchema: remotePortEnterRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePortEnterResultSchema,
    },
  }),
  defineRoute({
    id: "port-unforward",
    method: "POST",
    path: "/api/ports/unforward",
    auth: "bearer",
    scopes: ["ports:forward"],
    request: { bodyKind: "json", jsonSchema: remotePortUnforwardRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "procedure-call",
    method: "POST",
    path: "/api/git/call",
    auth: "bearer",
    scopes: [],
    scopeResolution: "procedure-defined",
    request: { bodyKind: "json", jsonSchema: remoteGitCallPayloadSchema },
    response: {
      wireKind: "procedure-result",
      status: 200,
    },
  }),
  defineRoute({
    id: "project-command",
    method: "POST",
    path: "/api/projects/command",
    auth: "bearer",
    scopes: ["projects:manage"],
    request: { bodyKind: "json", jsonSchema: remoteProjectCommandSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteProjectCommandResultSchema,
    },
  }),
  defineRoute({
    id: "project-settings",
    method: "GET",
    path: "/api/projects/{projectId}/settings",
    auth: "bearer",
    scopes: ["projects:manage"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteProjectSettingsSchema,
    },
  }),
  defineRoute({
    id: "push-config",
    method: "GET",
    path: "/api/push/config",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteWebPushConfigResultSchema,
    },
  }),
  defineRoute({
    id: "push-register",
    method: "POST",
    path: "/api/push/register",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: remotePushRegistrationSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePushRegistrationResultSchema,
    },
  }),
  defineRoute({
    id: "push-unregister",
    method: "POST",
    path: "/api/push/unregister",
    auth: "bearer",
    scopes: ["session:operate"],
    request: { bodyKind: "json", jsonSchema: remotePushUnregisterSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePushRegistrationResultSchema,
    },
  }),
];
