import { defineRoute, remoteOkResponseSchema } from "../helpers";
import { auditEvent, noAudit } from "../../auditKinds";
import {
  attachmentUploadQuerySchema,
  attachmentUploadResultSchema,
  browserStateResultSchema,
  imageTicketRequestBodySchema,
  imageTicketResponseSchema,
  localImageQuerySchema,
  prWatchInputSchema,
  prWatchAgentSyncSchema,
  prWatchKeySchema,
  prWatchReadQuerySchema,
  prWatchReadResultSchema,
  prWatchUpsertResultSchema,
  remoteBrowserCommandSchema,
  remoteGitCallPayloadSchema,
  remotePortEnterRequestSchema,
  remotePortEnterResultSchema,
  remotePortForwardRequestSchema,
  remotePortForwardResultSchema,
  remotePortUnforwardRequestSchema,
  remotePortsStateSchema,
  remoteProjectCommandResponseSchema,
  remoteProjectCommandSchema,
  remoteProjectSettingsSchema,
  remotePushRegistrationResultSchema,
  remotePushRegistrationSchema,
  remotePushUnregisterSchema,
  remoteScheduleCommandSchema,
  remoteScheduleRunsQuerySchema,
  remoteScheduleRunsResponseSchema,
  remoteSchedulesResponseSchema,
  remoteWebPushConfigResultSchema,
  runtimeImageQuerySchema,
} from "../routeSchemas";
import type { RemoteHttpRouteContract } from "../types";

export const workspaceRoutes: readonly RemoteHttpRouteContract[] = [
  defineRoute({
    id: "local-image",
    method: "GET",
    path: "/api/files/image",
    // Gate 6 item 4.6 (S6): the query credential is now the one-time,
    // path-scoped image ticket (`?ticket=`, minted by
    // `POST /api/files/image-ticket`); the `?access_token=` bearer-on-URL
    // acceptance is REMOVED (bearer-in-URL leaks into proxy/relay access
    // logs). The auth label keeps its historical `bearer-or-query` value on
    // purpose: the wire shape is still "Authorization header or query
    // credential", so native consumers' strict auth-kind parsers stay valid,
    // and their bearer-header image fetches keep working unchanged.
    auth: "bearer-or-query",
    scopes: ["session:read"],
    audit: auditEvent("file_read"),
    queryParameters: ["path", "ticket"],
    request: { bodyKind: "empty", querySchema: localImageQuerySchema },
    response: {
      wireKind: "binary",
      status: 200,
      contentType: "image/*",
    },
  }),
  defineRoute({
    id: "local-image-ticket",
    method: "POST",
    path: "/api/files/image-ticket",
    auth: "bearer",
    scopes: ["session:read"],
    audit: auditEvent("file_read"),
    queryParameters: [],
    request: { bodyKind: "json", jsonSchema: imageTicketRequestBodySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: imageTicketResponseSchema,
    },
  }),
  defineRoute({
    id: "runtime-image",
    method: "GET",
    path: "/api/threads/{threadId}/items/{itemId}/image",
    // Gate 6 item 4.6 (S6): same ticket affordance as `local-image` — the
    // ticket is minted for the exact JSON `path` value and consumed once;
    // the `?access_token=` acceptance is gone (see the sibling route).
    auth: "bearer-or-query",
    scopes: ["session:read"],
    audit: auditEvent("file_read"),
    queryParameters: ["path", "ticket"],
    request: { bodyKind: "empty", querySchema: runtimeImageQuerySchema },
    response: {
      wireKind: "binary",
      status: 200,
      contentType: "image/*",
    },
  }),
  defineRoute({
    id: "attachment-upload",
    method: "POST",
    path: "/api/files/attachment",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("file_write"),
    queryParameters: ["threadId", "name"],
    request: { bodyKind: "raw-upload", querySchema: attachmentUploadQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: attachmentUploadResultSchema,
    },
  }),
  defineRoute({
    id: "schedules-read",
    method: "GET",
    path: "/api/schedules",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteSchedulesResponseSchema,
    },
  }),
  defineRoute({
    id: "schedules-command",
    method: "POST",
    path: "/api/schedules/command",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remoteScheduleCommandSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteSchedulesResponseSchema,
    },
  }),
  defineRoute({
    id: "schedule-runs-read",
    method: "GET",
    path: "/api/schedules/runs",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    queryParameters: ["id"],
    request: { bodyKind: "empty", querySchema: remoteScheduleRunsQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteScheduleRunsResponseSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-read",
    method: "GET",
    path: "/api/pr-watches",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    queryParameters: ["projectId", "prNumber"],
    request: { bodyKind: "empty", querySchema: prWatchReadQuerySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: prWatchReadResultSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-check",
    method: "POST",
    path: "/api/pr-watches/check",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: prWatchKeySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-agent-sync",
    method: "POST",
    path: "/api/pr-watches/agent",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: prWatchAgentSyncSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-upsert",
    method: "POST",
    path: "/api/pr-watches",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: prWatchInputSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: prWatchUpsertResultSchema,
    },
  }),
  defineRoute({
    id: "pr-watch-delete",
    method: "DELETE",
    path: "/api/pr-watches",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: prWatchKeySchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "browser-state",
    method: "GET",
    path: "/api/browser/state",
    auth: "bearer",
    scopes: ["session:read"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: browserStateResultSchema,
    },
  }),
  defineRoute({
    id: "browser-command",
    method: "POST",
    path: "/api/browser/command",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remoteBrowserCommandSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: browserStateResultSchema,
    },
  }),
  defineRoute({
    id: "ports-read",
    method: "GET",
    path: "/api/ports",
    auth: "bearer",
    scopes: ["ports:forward"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePortsStateSchema,
    },
  }),
  defineRoute({
    id: "port-forward",
    method: "POST",
    path: "/api/ports/forward",
    auth: "bearer",
    scopes: ["ports:forward"],
    audit: auditEvent("forward_open"),
    request: { bodyKind: "json", jsonSchema: remotePortForwardRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePortForwardResultSchema,
    },
  }),
  defineRoute({
    id: "port-enter",
    method: "POST",
    path: "/api/ports/enter",
    auth: "bearer",
    scopes: ["ports:forward"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remotePortEnterRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePortEnterResultSchema,
    },
  }),
  defineRoute({
    id: "port-unforward",
    method: "POST",
    path: "/api/ports/unforward",
    auth: "bearer",
    scopes: ["ports:forward"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remotePortUnforwardRequestSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteOkResponseSchema,
    },
  }),
  defineRoute({
    id: "procedure-call",
    method: "POST",
    path: "/api/git/call",
    auth: "bearer",
    scopes: [],
    audit: auditEvent("procedure"),
    scopeResolution: "procedure-defined",
    request: { bodyKind: "json", jsonSchema: remoteGitCallPayloadSchema },
    response: {
      wireKind: "procedure-result",
      status: 200,
    },
  }),
  defineRoute({
    id: "project-command",
    method: "POST",
    path: "/api/projects/command",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: auditEvent("mutate"),
    // Legacy kinds are dispatched directly (no receipt); the narrow
    // catalog-mutation kinds REQUIRE the command-id header (refused before any
    // effect without it) and run under the receipt. The per-request bounded
    // result declaration (`x-poracode-project-command-result: bounded-v1`, like
    // the command-id header not modeled by this descriptor) is a separate
    // negotiation: under it EVERY kind requires the id and runs under the
    // receipt, and a declared request without one is refused before any effect.
    idempotency: "command-id-header-for-catalog-kinds",
    request: { bodyKind: "json", jsonSchema: remoteProjectCommandSchema },
    response: {
      wireKind: "json",
      status: 200,
      // Union: legacy kinds keep the complete result, catalog mutations
      // answer with the bounded acknowledgement.
      jsonSchema: remoteProjectCommandResponseSchema,
    },
  }),
  defineRoute({
    id: "project-settings",
    method: "GET",
    path: "/api/projects/{projectId}/settings",
    auth: "bearer",
    scopes: ["projects:manage"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteProjectSettingsSchema,
    },
  }),
  defineRoute({
    id: "push-config",
    method: "GET",
    path: "/api/push/config",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: noAudit("read"),
    request: { bodyKind: "empty" },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remoteWebPushConfigResultSchema,
    },
  }),
  defineRoute({
    id: "push-register",
    method: "POST",
    path: "/api/push/register",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remotePushRegistrationSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePushRegistrationResultSchema,
    },
  }),
  defineRoute({
    id: "push-unregister",
    method: "POST",
    path: "/api/push/unregister",
    auth: "bearer",
    scopes: ["session:operate"],
    audit: auditEvent("mutate"),
    request: { bodyKind: "json", jsonSchema: remotePushUnregisterSchema },
    response: {
      wireKind: "json",
      status: 200,
      jsonSchema: remotePushRegistrationResultSchema,
    },
  }),
];
